<?xml version="1.0" encoding="UTF-8" ?>
<Package name="asr2" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions />
    <Dialogs />
    <Resources>
        <File name="asr2" src="lib/asr2.py" />
        <File name="__init__" src="lib/__init__.py" />
        <File name="AbcdkSoundReceiver" src="lib/abcdk/AbcdkSoundReceiver/AbcdkSoundReceiver.py" />
        <File name="__init__" src="lib/abcdk/AbcdkSoundReceiver/__init__.py" />
        <File name="sound_analyser" src="lib/abcdk/AbcdkSoundReceiver/sound_analyser.py" />
        <File name="vad" src="lib/abcdk/AbcdkSoundReceiver/vad.py" />
        <File name="__init__" src="lib/abcdk/__init__.py" />
        <File name="LedsDcm" src="lib/abcdk/leds/LedsDcm.py" />
        <File name="__init__" src="lib/abcdk/leds/__init__.py" />
        <File name="__init__" src="lib/abcdk/python_speech_features/__init__.py" />
        <File name="base" src="lib/abcdk/python_speech_features/base.py" />
        <File name="sigproc" src="lib/abcdk/python_speech_features/sigproc.py" />
        <File name="__init__" src="lib/abcdk/sound/__init__.py" />
        <File name="analyse" src="lib/abcdk/sound/analyse.py" />
        <File name="elan_generator" src="lib/abcdk/sound/elan_generator.py" />
        <File name="fatBass" src="lib/abcdk/sound/fatBass.py" />
        <File name="freespeech" src="lib/abcdk/sound/freespeech.py" />
        <File name="language_tools" src="lib/abcdk/sound/language_tools.py" />
        <File name="midi" src="lib/abcdk/sound/midi.py" />
        <File name="play" src="lib/abcdk/sound/play.py" />
        <File name="wav" src="lib/abcdk/sound/wav.py" />
        <File name="wav_tools" src="lib/abcdk/sound/wav_tools.py" />
        <File name="__init__" src="lib/abcdk/stk/__init__.py" />
        <File name="events" src="lib/abcdk/stk/events.py" />
        <File name="logging" src="lib/abcdk/stk/logging.py" />
        <File name="runner" src="lib/abcdk/stk/runner.py" />
        <File name="services" src="lib/abcdk/stk/services.py" />
        <File name="__init__" src="lib/otherlibs/__init__.py" />
        <File name="__init__" src="lib/otherlibs/oauth2client/__init__.py" />
        <File name="__init__" src="lib/otherlibs/oauth2client/__init__.pyc" />
        <File name="_helpers" src="lib/otherlibs/oauth2client/_helpers.py" />
        <File name="_helpers" src="lib/otherlibs/oauth2client/_helpers.pyc" />
        <File name="_openssl_crypt" src="lib/otherlibs/oauth2client/_openssl_crypt.py" />
        <File name="_openssl_crypt" src="lib/otherlibs/oauth2client/_openssl_crypt.pyc" />
        <File name="_pkce" src="lib/otherlibs/oauth2client/_pkce.py" />
        <File name="_pkce" src="lib/otherlibs/oauth2client/_pkce.pyc" />
        <File name="_pure_python_crypt" src="lib/otherlibs/oauth2client/_pure_python_crypt.py" />
        <File name="_pure_python_crypt" src="lib/otherlibs/oauth2client/_pure_python_crypt.pyc" />
        <File name="_pycrypto_crypt" src="lib/otherlibs/oauth2client/_pycrypto_crypt.py" />
        <File name="_pycrypto_crypt" src="lib/otherlibs/oauth2client/_pycrypto_crypt.pyc" />
        <File name="client" src="lib/otherlibs/oauth2client/client.py" />
        <File name="client" src="lib/otherlibs/oauth2client/client.pyc" />
        <File name="clientsecrets" src="lib/otherlibs/oauth2client/clientsecrets.py" />
        <File name="clientsecrets" src="lib/otherlibs/oauth2client/clientsecrets.pyc" />
        <File name="__init__" src="lib/otherlibs/oauth2client/contrib/__init__.py" />
        <File name="__init__" src="lib/otherlibs/oauth2client/contrib/__init__.pyc" />
        <File name="_appengine_ndb" src="lib/otherlibs/oauth2client/contrib/_appengine_ndb.py" />
        <File name="_appengine_ndb" src="lib/otherlibs/oauth2client/contrib/_appengine_ndb.pyc" />
        <File name="_metadata" src="lib/otherlibs/oauth2client/contrib/_metadata.py" />
        <File name="_metadata" src="lib/otherlibs/oauth2client/contrib/_metadata.pyc" />
        <File name="appengine" src="lib/otherlibs/oauth2client/contrib/appengine.py" />
        <File name="appengine" src="lib/otherlibs/oauth2client/contrib/appengine.pyc" />
        <File name="devshell" src="lib/otherlibs/oauth2client/contrib/devshell.py" />
        <File name="devshell" src="lib/otherlibs/oauth2client/contrib/devshell.pyc" />
        <File name="dictionary_storage" src="lib/otherlibs/oauth2client/contrib/dictionary_storage.py" />
        <File name="dictionary_storage" src="lib/otherlibs/oauth2client/contrib/dictionary_storage.pyc" />
        <File name="__init__" src="lib/otherlibs/oauth2client/contrib/django_util/__init__.py" />
        <File name="__init__" src="lib/otherlibs/oauth2client/contrib/django_util/__init__.pyc" />
        <File name="apps" src="lib/otherlibs/oauth2client/contrib/django_util/apps.py" />
        <File name="apps" src="lib/otherlibs/oauth2client/contrib/django_util/apps.pyc" />
        <File name="decorators" src="lib/otherlibs/oauth2client/contrib/django_util/decorators.py" />
        <File name="decorators" src="lib/otherlibs/oauth2client/contrib/django_util/decorators.pyc" />
        <File name="models" src="lib/otherlibs/oauth2client/contrib/django_util/models.py" />
        <File name="models" src="lib/otherlibs/oauth2client/contrib/django_util/models.pyc" />
        <File name="signals" src="lib/otherlibs/oauth2client/contrib/django_util/signals.py" />
        <File name="signals" src="lib/otherlibs/oauth2client/contrib/django_util/signals.pyc" />
        <File name="site" src="lib/otherlibs/oauth2client/contrib/django_util/site.py" />
        <File name="site" src="lib/otherlibs/oauth2client/contrib/django_util/site.pyc" />
        <File name="storage" src="lib/otherlibs/oauth2client/contrib/django_util/storage.py" />
        <File name="storage" src="lib/otherlibs/oauth2client/contrib/django_util/storage.pyc" />
        <File name="views" src="lib/otherlibs/oauth2client/contrib/django_util/views.py" />
        <File name="views" src="lib/otherlibs/oauth2client/contrib/django_util/views.pyc" />
        <File name="flask_util" src="lib/otherlibs/oauth2client/contrib/flask_util.py" />
        <File name="flask_util" src="lib/otherlibs/oauth2client/contrib/flask_util.pyc" />
        <File name="gce" src="lib/otherlibs/oauth2client/contrib/gce.py" />
        <File name="gce" src="lib/otherlibs/oauth2client/contrib/gce.pyc" />
        <File name="keyring_storage" src="lib/otherlibs/oauth2client/contrib/keyring_storage.py" />
        <File name="keyring_storage" src="lib/otherlibs/oauth2client/contrib/keyring_storage.pyc" />
        <File name="multiprocess_file_storage" src="lib/otherlibs/oauth2client/contrib/multiprocess_file_storage.py" />
        <File name="multiprocess_file_storage" src="lib/otherlibs/oauth2client/contrib/multiprocess_file_storage.pyc" />
        <File name="sqlalchemy" src="lib/otherlibs/oauth2client/contrib/sqlalchemy.py" />
        <File name="sqlalchemy" src="lib/otherlibs/oauth2client/contrib/sqlalchemy.pyc" />
        <File name="xsrfutil" src="lib/otherlibs/oauth2client/contrib/xsrfutil.py" />
        <File name="xsrfutil" src="lib/otherlibs/oauth2client/contrib/xsrfutil.pyc" />
        <File name="crypt" src="lib/otherlibs/oauth2client/crypt.py" />
        <File name="crypt" src="lib/otherlibs/oauth2client/crypt.pyc" />
        <File name="file" src="lib/otherlibs/oauth2client/file.py" />
        <File name="file" src="lib/otherlibs/oauth2client/file.pyc" />
        <File name="service_account" src="lib/otherlibs/oauth2client/service_account.py" />
        <File name="service_account" src="lib/otherlibs/oauth2client/service_account.pyc" />
        <File name="tools" src="lib/otherlibs/oauth2client/tools.py" />
        <File name="tools" src="lib/otherlibs/oauth2client/tools.pyc" />
        <File name="transport" src="lib/otherlibs/oauth2client/transport.py" />
        <File name="transport" src="lib/otherlibs/oauth2client/transport.pyc" />
        <File name="DESCRIPTION" src="lib/otherlibs/cachetools-2.0.1.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/cachetools-2.0.1.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/cachetools-2.0.1.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/cachetools-2.0.1.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/cachetools-2.0.1.dist-info/WHEEL" />
        <File name="metadata" src="lib/otherlibs/cachetools-2.0.1.dist-info/metadata.json" />
        <File name="top_level" src="lib/otherlibs/cachetools-2.0.1.dist-info/top_level.txt" />
        <File name="__init__" src="lib/otherlibs/cachetools/__init__.py" />
        <File name="__init__" src="lib/otherlibs/cachetools/__init__.pyc" />
        <File name="abc" src="lib/otherlibs/cachetools/abc.py" />
        <File name="abc" src="lib/otherlibs/cachetools/abc.pyc" />
        <File name="cache" src="lib/otherlibs/cachetools/cache.py" />
        <File name="cache" src="lib/otherlibs/cachetools/cache.pyc" />
        <File name="func" src="lib/otherlibs/cachetools/func.py" />
        <File name="func" src="lib/otherlibs/cachetools/func.pyc" />
        <File name="keys" src="lib/otherlibs/cachetools/keys.py" />
        <File name="keys" src="lib/otherlibs/cachetools/keys.pyc" />
        <File name="lfu" src="lib/otherlibs/cachetools/lfu.py" />
        <File name="lfu" src="lib/otherlibs/cachetools/lfu.pyc" />
        <File name="lru" src="lib/otherlibs/cachetools/lru.py" />
        <File name="lru" src="lib/otherlibs/cachetools/lru.pyc" />
        <File name="rr" src="lib/otherlibs/cachetools/rr.py" />
        <File name="rr" src="lib/otherlibs/cachetools/rr.pyc" />
        <File name="ttl" src="lib/otherlibs/cachetools/ttl.py" />
        <File name="ttl" src="lib/otherlibs/cachetools/ttl.pyc" />
        <File name="__init__" src="lib/otherlibs/google/api/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/api/__init__.pyc" />
        <File name="annotations_pb2" src="lib/otherlibs/google/api/annotations_pb2.py" />
        <File name="annotations_pb2" src="lib/otherlibs/google/api/annotations_pb2.pyc" />
        <File name="auth_pb2" src="lib/otherlibs/google/api/auth_pb2.py" />
        <File name="auth_pb2" src="lib/otherlibs/google/api/auth_pb2.pyc" />
        <File name="backend_pb2" src="lib/otherlibs/google/api/backend_pb2.py" />
        <File name="backend_pb2" src="lib/otherlibs/google/api/backend_pb2.pyc" />
        <File name="billing_pb2" src="lib/otherlibs/google/api/billing_pb2.py" />
        <File name="billing_pb2" src="lib/otherlibs/google/api/billing_pb2.pyc" />
        <File name="config_change_pb2" src="lib/otherlibs/google/api/config_change_pb2.py" />
        <File name="config_change_pb2" src="lib/otherlibs/google/api/config_change_pb2.pyc" />
        <File name="consumer_pb2" src="lib/otherlibs/google/api/consumer_pb2.py" />
        <File name="consumer_pb2" src="lib/otherlibs/google/api/consumer_pb2.pyc" />
        <File name="context_pb2" src="lib/otherlibs/google/api/context_pb2.py" />
        <File name="context_pb2" src="lib/otherlibs/google/api/context_pb2.pyc" />
        <File name="control_pb2" src="lib/otherlibs/google/api/control_pb2.py" />
        <File name="control_pb2" src="lib/otherlibs/google/api/control_pb2.pyc" />
        <File name="distribution_pb2" src="lib/otherlibs/google/api/distribution_pb2.py" />
        <File name="distribution_pb2" src="lib/otherlibs/google/api/distribution_pb2.pyc" />
        <File name="documentation_pb2" src="lib/otherlibs/google/api/documentation_pb2.py" />
        <File name="documentation_pb2" src="lib/otherlibs/google/api/documentation_pb2.pyc" />
        <File name="endpoint_pb2" src="lib/otherlibs/google/api/endpoint_pb2.py" />
        <File name="endpoint_pb2" src="lib/otherlibs/google/api/endpoint_pb2.pyc" />
        <File name="http_pb2" src="lib/otherlibs/google/api/http_pb2.py" />
        <File name="http_pb2" src="lib/otherlibs/google/api/http_pb2.pyc" />
        <File name="httpbody_pb2" src="lib/otherlibs/google/api/httpbody_pb2.py" />
        <File name="httpbody_pb2" src="lib/otherlibs/google/api/httpbody_pb2.pyc" />
        <File name="label_pb2" src="lib/otherlibs/google/api/label_pb2.py" />
        <File name="label_pb2" src="lib/otherlibs/google/api/label_pb2.pyc" />
        <File name="log_pb2" src="lib/otherlibs/google/api/log_pb2.py" />
        <File name="log_pb2" src="lib/otherlibs/google/api/log_pb2.pyc" />
        <File name="logging_pb2" src="lib/otherlibs/google/api/logging_pb2.py" />
        <File name="logging_pb2" src="lib/otherlibs/google/api/logging_pb2.pyc" />
        <File name="metric_pb2" src="lib/otherlibs/google/api/metric_pb2.py" />
        <File name="metric_pb2" src="lib/otherlibs/google/api/metric_pb2.pyc" />
        <File name="monitored_resource_pb2" src="lib/otherlibs/google/api/monitored_resource_pb2.py" />
        <File name="monitored_resource_pb2" src="lib/otherlibs/google/api/monitored_resource_pb2.pyc" />
        <File name="monitoring_pb2" src="lib/otherlibs/google/api/monitoring_pb2.py" />
        <File name="monitoring_pb2" src="lib/otherlibs/google/api/monitoring_pb2.pyc" />
        <File name="service_pb2" src="lib/otherlibs/google/api/service_pb2.py" />
        <File name="service_pb2" src="lib/otherlibs/google/api/service_pb2.pyc" />
        <File name="system_parameter_pb2" src="lib/otherlibs/google/api/system_parameter_pb2.py" />
        <File name="system_parameter_pb2" src="lib/otherlibs/google/api/system_parameter_pb2.pyc" />
        <File name="usage_pb2" src="lib/otherlibs/google/api/usage_pb2.py" />
        <File name="usage_pb2" src="lib/otherlibs/google/api/usage_pb2.pyc" />
        <File name="__init__" src="lib/otherlibs/google/api_core/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/api_core/__init__.pyc" />
        <File name="datetime_helpers" src="lib/otherlibs/google/api_core/datetime_helpers.py" />
        <File name="datetime_helpers" src="lib/otherlibs/google/api_core/datetime_helpers.pyc" />
        <File name="exceptions" src="lib/otherlibs/google/api_core/exceptions.py" />
        <File name="exceptions" src="lib/otherlibs/google/api_core/exceptions.pyc" />
        <File name="__init__" src="lib/otherlibs/google/api_core/future/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/api_core/future/__init__.pyc" />
        <File name="_helpers" src="lib/otherlibs/google/api_core/future/_helpers.py" />
        <File name="_helpers" src="lib/otherlibs/google/api_core/future/_helpers.pyc" />
        <File name="base" src="lib/otherlibs/google/api_core/future/base.py" />
        <File name="base" src="lib/otherlibs/google/api_core/future/base.pyc" />
        <File name="polling" src="lib/otherlibs/google/api_core/future/polling.py" />
        <File name="polling" src="lib/otherlibs/google/api_core/future/polling.pyc" />
        <File name="__init__" src="lib/otherlibs/google/api_core/gapic_v1/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/api_core/gapic_v1/__init__.pyc" />
        <File name="client_info" src="lib/otherlibs/google/api_core/gapic_v1/client_info.py" />
        <File name="client_info" src="lib/otherlibs/google/api_core/gapic_v1/client_info.pyc" />
        <File name="config" src="lib/otherlibs/google/api_core/gapic_v1/config.py" />
        <File name="config" src="lib/otherlibs/google/api_core/gapic_v1/config.pyc" />
        <File name="method" src="lib/otherlibs/google/api_core/gapic_v1/method.py" />
        <File name="method" src="lib/otherlibs/google/api_core/gapic_v1/method.pyc" />
        <File name="routing_header" src="lib/otherlibs/google/api_core/gapic_v1/routing_header.py" />
        <File name="routing_header" src="lib/otherlibs/google/api_core/gapic_v1/routing_header.pyc" />
        <File name="general_helpers" src="lib/otherlibs/google/api_core/general_helpers.py" />
        <File name="general_helpers" src="lib/otherlibs/google/api_core/general_helpers.pyc" />
        <File name="grpc_helpers" src="lib/otherlibs/google/api_core/grpc_helpers.py" />
        <File name="grpc_helpers" src="lib/otherlibs/google/api_core/grpc_helpers.pyc" />
        <File name="operation" src="lib/otherlibs/google/api_core/operation.py" />
        <File name="operation" src="lib/otherlibs/google/api_core/operation.pyc" />
        <File name="__init__" src="lib/otherlibs/google/api_core/operations_v1/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/api_core/operations_v1/__init__.pyc" />
        <File name="operations_client" src="lib/otherlibs/google/api_core/operations_v1/operations_client.py" />
        <File name="operations_client" src="lib/otherlibs/google/api_core/operations_v1/operations_client.pyc" />
        <File name="operations_client_config" src="lib/otherlibs/google/api_core/operations_v1/operations_client_config.py" />
        <File name="operations_client_config" src="lib/otherlibs/google/api_core/operations_v1/operations_client_config.pyc" />
        <File name="page_iterator" src="lib/otherlibs/google/api_core/page_iterator.py" />
        <File name="page_iterator" src="lib/otherlibs/google/api_core/page_iterator.pyc" />
        <File name="path_template" src="lib/otherlibs/google/api_core/path_template.py" />
        <File name="path_template" src="lib/otherlibs/google/api_core/path_template.pyc" />
        <File name="protobuf_helpers" src="lib/otherlibs/google/api_core/protobuf_helpers.py" />
        <File name="protobuf_helpers" src="lib/otherlibs/google/api_core/protobuf_helpers.pyc" />
        <File name="retry" src="lib/otherlibs/google/api_core/retry.py" />
        <File name="retry" src="lib/otherlibs/google/api_core/retry.pyc" />
        <File name="timeout" src="lib/otherlibs/google/api_core/timeout.py" />
        <File name="timeout" src="lib/otherlibs/google/api_core/timeout.pyc" />
        <File name="__init__" src="lib/otherlibs/google/auth/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/auth/__init__.pyc" />
        <File name="_cloud_sdk" src="lib/otherlibs/google/auth/_cloud_sdk.py" />
        <File name="_cloud_sdk" src="lib/otherlibs/google/auth/_cloud_sdk.pyc" />
        <File name="_default" src="lib/otherlibs/google/auth/_default.py" />
        <File name="_default" src="lib/otherlibs/google/auth/_default.pyc" />
        <File name="_helpers" src="lib/otherlibs/google/auth/_helpers.py" />
        <File name="_helpers" src="lib/otherlibs/google/auth/_helpers.pyc" />
        <File name="_oauth2client" src="lib/otherlibs/google/auth/_oauth2client.py" />
        <File name="_oauth2client" src="lib/otherlibs/google/auth/_oauth2client.pyc" />
        <File name="_service_account_info" src="lib/otherlibs/google/auth/_service_account_info.py" />
        <File name="_service_account_info" src="lib/otherlibs/google/auth/_service_account_info.pyc" />
        <File name="app_engine" src="lib/otherlibs/google/auth/app_engine.py" />
        <File name="app_engine" src="lib/otherlibs/google/auth/app_engine.pyc" />
        <File name="__init__" src="lib/otherlibs/google/auth/compute_engine/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/auth/compute_engine/__init__.pyc" />
        <File name="_metadata" src="lib/otherlibs/google/auth/compute_engine/_metadata.py" />
        <File name="_metadata" src="lib/otherlibs/google/auth/compute_engine/_metadata.pyc" />
        <File name="credentials" src="lib/otherlibs/google/auth/compute_engine/credentials.py" />
        <File name="credentials" src="lib/otherlibs/google/auth/compute_engine/credentials.pyc" />
        <File name="credentials" src="lib/otherlibs/google/auth/credentials.py" />
        <File name="credentials" src="lib/otherlibs/google/auth/credentials.pyc" />
        <File name="__init__" src="lib/otherlibs/google/auth/crypt/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/auth/crypt/__init__.pyc" />
        <File name="_python_rsa" src="lib/otherlibs/google/auth/crypt/_python_rsa.py" />
        <File name="_python_rsa" src="lib/otherlibs/google/auth/crypt/_python_rsa.pyc" />
        <File name="base" src="lib/otherlibs/google/auth/crypt/base.py" />
        <File name="base" src="lib/otherlibs/google/auth/crypt/base.pyc" />
        <File name="rsa" src="lib/otherlibs/google/auth/crypt/rsa.py" />
        <File name="rsa" src="lib/otherlibs/google/auth/crypt/rsa.pyc" />
        <File name="environment_vars" src="lib/otherlibs/google/auth/environment_vars.py" />
        <File name="environment_vars" src="lib/otherlibs/google/auth/environment_vars.pyc" />
        <File name="exceptions" src="lib/otherlibs/google/auth/exceptions.py" />
        <File name="exceptions" src="lib/otherlibs/google/auth/exceptions.pyc" />
        <File name="iam" src="lib/otherlibs/google/auth/iam.py" />
        <File name="iam" src="lib/otherlibs/google/auth/iam.pyc" />
        <File name="jwt" src="lib/otherlibs/google/auth/jwt.py" />
        <File name="jwt" src="lib/otherlibs/google/auth/jwt.pyc" />
        <File name="__init__" src="lib/otherlibs/google/auth/transport/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/auth/transport/__init__.pyc" />
        <File name="_http_client" src="lib/otherlibs/google/auth/transport/_http_client.py" />
        <File name="_http_client" src="lib/otherlibs/google/auth/transport/_http_client.pyc" />
        <File name="grpc" src="lib/otherlibs/google/auth/transport/grpc.py" />
        <File name="grpc" src="lib/otherlibs/google/auth/transport/grpc.pyc" />
        <File name="requests" src="lib/otherlibs/google/auth/transport/requests.py" />
        <File name="requests" src="lib/otherlibs/google/auth/transport/requests.pyc" />
        <File name="urllib3" src="lib/otherlibs/google/auth/transport/urllib3.py" />
        <File name="urllib3" src="lib/otherlibs/google/auth/transport/urllib3.pyc" />
        <File name="speech" src="lib/otherlibs/google/cloud/speech.py" />
        <File name="speech" src="lib/otherlibs/google/cloud/speech.pyc" />
        <File name="__init__" src="lib/otherlibs/google/cloud/speech_v1/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/cloud/speech_v1/__init__.pyc" />
        <File name="__init__" src="lib/otherlibs/google/cloud/speech_v1/gapic/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/cloud/speech_v1/gapic/__init__.pyc" />
        <File name="enums" src="lib/otherlibs/google/cloud/speech_v1/gapic/enums.py" />
        <File name="enums" src="lib/otherlibs/google/cloud/speech_v1/gapic/enums.pyc" />
        <File name="speech_client" src="lib/otherlibs/google/cloud/speech_v1/gapic/speech_client.py" />
        <File name="speech_client" src="lib/otherlibs/google/cloud/speech_v1/gapic/speech_client.pyc" />
        <File name="speech_client_config" src="lib/otherlibs/google/cloud/speech_v1/gapic/speech_client_config.py" />
        <File name="speech_client_config" src="lib/otherlibs/google/cloud/speech_v1/gapic/speech_client_config.pyc" />
        <File name="helpers" src="lib/otherlibs/google/cloud/speech_v1/helpers.py" />
        <File name="helpers" src="lib/otherlibs/google/cloud/speech_v1/helpers.pyc" />
        <File name="__init__" src="lib/otherlibs/google/cloud/speech_v1/proto/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/cloud/speech_v1/proto/__init__.pyc" />
        <File name="cloud_speech_pb2" src="lib/otherlibs/google/cloud/speech_v1/proto/cloud_speech_pb2.py" />
        <File name="cloud_speech_pb2" src="lib/otherlibs/google/cloud/speech_v1/proto/cloud_speech_pb2.pyc" />
        <File name="cloud_speech_pb2_grpc" src="lib/otherlibs/google/cloud/speech_v1/proto/cloud_speech_pb2_grpc.py" />
        <File name="cloud_speech_pb2_grpc" src="lib/otherlibs/google/cloud/speech_v1/proto/cloud_speech_pb2_grpc.pyc" />
        <File name="types" src="lib/otherlibs/google/cloud/speech_v1/types.py" />
        <File name="types" src="lib/otherlibs/google/cloud/speech_v1/types.pyc" />
        <File name="__init__" src="lib/otherlibs/google/logging/type/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/logging/type/__init__.pyc" />
        <File name="http_request_pb2" src="lib/otherlibs/google/logging/type/http_request_pb2.py" />
        <File name="http_request_pb2" src="lib/otherlibs/google/logging/type/http_request_pb2.pyc" />
        <File name="log_severity_pb2" src="lib/otherlibs/google/logging/type/log_severity_pb2.py" />
        <File name="log_severity_pb2" src="lib/otherlibs/google/logging/type/log_severity_pb2.pyc" />
        <File name="__init__" src="lib/otherlibs/google/longrunning/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/longrunning/__init__.pyc" />
        <File name="operations_grpc" src="lib/otherlibs/google/longrunning/operations_grpc.py" />
        <File name="operations_grpc" src="lib/otherlibs/google/longrunning/operations_grpc.pyc" />
        <File name="operations_grpc_pb2" src="lib/otherlibs/google/longrunning/operations_grpc_pb2.py" />
        <File name="operations_grpc_pb2" src="lib/otherlibs/google/longrunning/operations_grpc_pb2.pyc" />
        <File name="operations_pb2" src="lib/otherlibs/google/longrunning/operations_pb2.py" />
        <File name="operations_pb2" src="lib/otherlibs/google/longrunning/operations_pb2.pyc" />
        <File name="operations_proto" src="lib/otherlibs/google/longrunning/operations_proto.py" />
        <File name="operations_proto" src="lib/otherlibs/google/longrunning/operations_proto.pyc" />
        <File name="operations_proto_pb2" src="lib/otherlibs/google/longrunning/operations_proto_pb2.py" />
        <File name="operations_proto_pb2" src="lib/otherlibs/google/longrunning/operations_proto_pb2.pyc" />
        <File name="__init__" src="lib/otherlibs/google/oauth2/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/oauth2/__init__.pyc" />
        <File name="_client" src="lib/otherlibs/google/oauth2/_client.py" />
        <File name="_client" src="lib/otherlibs/google/oauth2/_client.pyc" />
        <File name="credentials" src="lib/otherlibs/google/oauth2/credentials.py" />
        <File name="credentials" src="lib/otherlibs/google/oauth2/credentials.pyc" />
        <File name="id_token" src="lib/otherlibs/google/oauth2/id_token.py" />
        <File name="id_token" src="lib/otherlibs/google/oauth2/id_token.pyc" />
        <File name="service_account" src="lib/otherlibs/google/oauth2/service_account.py" />
        <File name="service_account" src="lib/otherlibs/google/oauth2/service_account.pyc" />
        <File name="__init__" src="lib/otherlibs/google/protobuf/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/protobuf/__init__.pyc" />
        <File name="any_pb2" src="lib/otherlibs/google/protobuf/any_pb2.py" />
        <File name="any_pb2" src="lib/otherlibs/google/protobuf/any_pb2.pyc" />
        <File name="any_test_pb2" src="lib/otherlibs/google/protobuf/any_test_pb2.py" />
        <File name="any_test_pb2" src="lib/otherlibs/google/protobuf/any_test_pb2.pyc" />
        <File name="api_pb2" src="lib/otherlibs/google/protobuf/api_pb2.py" />
        <File name="api_pb2" src="lib/otherlibs/google/protobuf/api_pb2.pyc" />
        <File name="__init__" src="lib/otherlibs/google/protobuf/compiler/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/protobuf/compiler/__init__.pyc" />
        <File name="plugin_pb2" src="lib/otherlibs/google/protobuf/compiler/plugin_pb2.py" />
        <File name="plugin_pb2" src="lib/otherlibs/google/protobuf/compiler/plugin_pb2.pyc" />
        <File name="descriptor" src="lib/otherlibs/google/protobuf/descriptor.py" />
        <File name="descriptor" src="lib/otherlibs/google/protobuf/descriptor.pyc" />
        <File name="descriptor_database" src="lib/otherlibs/google/protobuf/descriptor_database.py" />
        <File name="descriptor_database" src="lib/otherlibs/google/protobuf/descriptor_database.pyc" />
        <File name="descriptor_pb2" src="lib/otherlibs/google/protobuf/descriptor_pb2.py" />
        <File name="descriptor_pb2" src="lib/otherlibs/google/protobuf/descriptor_pb2.pyc" />
        <File name="descriptor_pool" src="lib/otherlibs/google/protobuf/descriptor_pool.py" />
        <File name="descriptor_pool" src="lib/otherlibs/google/protobuf/descriptor_pool.pyc" />
        <File name="duration_pb2" src="lib/otherlibs/google/protobuf/duration_pb2.py" />
        <File name="duration_pb2" src="lib/otherlibs/google/protobuf/duration_pb2.pyc" />
        <File name="empty_pb2" src="lib/otherlibs/google/protobuf/empty_pb2.py" />
        <File name="empty_pb2" src="lib/otherlibs/google/protobuf/empty_pb2.pyc" />
        <File name="field_mask_pb2" src="lib/otherlibs/google/protobuf/field_mask_pb2.py" />
        <File name="field_mask_pb2" src="lib/otherlibs/google/protobuf/field_mask_pb2.pyc" />
        <File name="__init__" src="lib/otherlibs/google/protobuf/internal/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/protobuf/internal/__init__.pyc" />
        <File name="_parameterized" src="lib/otherlibs/google/protobuf/internal/_parameterized.py" />
        <File name="_parameterized" src="lib/otherlibs/google/protobuf/internal/_parameterized.pyc" />
        <File name="any_test_pb2" src="lib/otherlibs/google/protobuf/internal/any_test_pb2.py" />
        <File name="any_test_pb2" src="lib/otherlibs/google/protobuf/internal/any_test_pb2.pyc" />
        <File name="api_implementation" src="lib/otherlibs/google/protobuf/internal/api_implementation.py" />
        <File name="api_implementation" src="lib/otherlibs/google/protobuf/internal/api_implementation.pyc" />
        <File name="containers" src="lib/otherlibs/google/protobuf/internal/containers.py" />
        <File name="containers" src="lib/otherlibs/google/protobuf/internal/containers.pyc" />
        <File name="decoder" src="lib/otherlibs/google/protobuf/internal/decoder.py" />
        <File name="decoder" src="lib/otherlibs/google/protobuf/internal/decoder.pyc" />
        <File name="descriptor_database_test" src="lib/otherlibs/google/protobuf/internal/descriptor_database_test.py" />
        <File name="descriptor_database_test" src="lib/otherlibs/google/protobuf/internal/descriptor_database_test.pyc" />
        <File name="descriptor_pool_test" src="lib/otherlibs/google/protobuf/internal/descriptor_pool_test.py" />
        <File name="descriptor_pool_test" src="lib/otherlibs/google/protobuf/internal/descriptor_pool_test.pyc" />
        <File name="descriptor_pool_test1_pb2" src="lib/otherlibs/google/protobuf/internal/descriptor_pool_test1_pb2.py" />
        <File name="descriptor_pool_test1_pb2" src="lib/otherlibs/google/protobuf/internal/descriptor_pool_test1_pb2.pyc" />
        <File name="descriptor_pool_test2_pb2" src="lib/otherlibs/google/protobuf/internal/descriptor_pool_test2_pb2.py" />
        <File name="descriptor_pool_test2_pb2" src="lib/otherlibs/google/protobuf/internal/descriptor_pool_test2_pb2.pyc" />
        <File name="descriptor_test" src="lib/otherlibs/google/protobuf/internal/descriptor_test.py" />
        <File name="descriptor_test" src="lib/otherlibs/google/protobuf/internal/descriptor_test.pyc" />
        <File name="encoder" src="lib/otherlibs/google/protobuf/internal/encoder.py" />
        <File name="encoder" src="lib/otherlibs/google/protobuf/internal/encoder.pyc" />
        <File name="enum_type_wrapper" src="lib/otherlibs/google/protobuf/internal/enum_type_wrapper.py" />
        <File name="enum_type_wrapper" src="lib/otherlibs/google/protobuf/internal/enum_type_wrapper.pyc" />
        <File name="factory_test1_pb2" src="lib/otherlibs/google/protobuf/internal/factory_test1_pb2.py" />
        <File name="factory_test1_pb2" src="lib/otherlibs/google/protobuf/internal/factory_test1_pb2.pyc" />
        <File name="factory_test2_pb2" src="lib/otherlibs/google/protobuf/internal/factory_test2_pb2.py" />
        <File name="factory_test2_pb2" src="lib/otherlibs/google/protobuf/internal/factory_test2_pb2.pyc" />
        <File name="file_options_test_pb2" src="lib/otherlibs/google/protobuf/internal/file_options_test_pb2.py" />
        <File name="file_options_test_pb2" src="lib/otherlibs/google/protobuf/internal/file_options_test_pb2.pyc" />
        <File name="generator_test" src="lib/otherlibs/google/protobuf/internal/generator_test.py" />
        <File name="generator_test" src="lib/otherlibs/google/protobuf/internal/generator_test.pyc" />
        <File name="__init__" src="lib/otherlibs/google/protobuf/internal/import_test_package/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/protobuf/internal/import_test_package/__init__.pyc" />
        <File name="inner_pb2" src="lib/otherlibs/google/protobuf/internal/import_test_package/inner_pb2.py" />
        <File name="inner_pb2" src="lib/otherlibs/google/protobuf/internal/import_test_package/inner_pb2.pyc" />
        <File name="outer_pb2" src="lib/otherlibs/google/protobuf/internal/import_test_package/outer_pb2.py" />
        <File name="outer_pb2" src="lib/otherlibs/google/protobuf/internal/import_test_package/outer_pb2.pyc" />
        <File name="json_format_test" src="lib/otherlibs/google/protobuf/internal/json_format_test.py" />
        <File name="json_format_test" src="lib/otherlibs/google/protobuf/internal/json_format_test.pyc" />
        <File name="message_factory_test" src="lib/otherlibs/google/protobuf/internal/message_factory_test.py" />
        <File name="message_factory_test" src="lib/otherlibs/google/protobuf/internal/message_factory_test.pyc" />
        <File name="message_listener" src="lib/otherlibs/google/protobuf/internal/message_listener.py" />
        <File name="message_listener" src="lib/otherlibs/google/protobuf/internal/message_listener.pyc" />
        <File name="message_set_extensions_pb2" src="lib/otherlibs/google/protobuf/internal/message_set_extensions_pb2.py" />
        <File name="message_set_extensions_pb2" src="lib/otherlibs/google/protobuf/internal/message_set_extensions_pb2.pyc" />
        <File name="message_test" src="lib/otherlibs/google/protobuf/internal/message_test.py" />
        <File name="message_test" src="lib/otherlibs/google/protobuf/internal/message_test.pyc" />
        <File name="missing_enum_values_pb2" src="lib/otherlibs/google/protobuf/internal/missing_enum_values_pb2.py" />
        <File name="missing_enum_values_pb2" src="lib/otherlibs/google/protobuf/internal/missing_enum_values_pb2.pyc" />
        <File name="more_extensions_dynamic_pb2" src="lib/otherlibs/google/protobuf/internal/more_extensions_dynamic_pb2.py" />
        <File name="more_extensions_dynamic_pb2" src="lib/otherlibs/google/protobuf/internal/more_extensions_dynamic_pb2.pyc" />
        <File name="more_extensions_pb2" src="lib/otherlibs/google/protobuf/internal/more_extensions_pb2.py" />
        <File name="more_extensions_pb2" src="lib/otherlibs/google/protobuf/internal/more_extensions_pb2.pyc" />
        <File name="more_messages_pb2" src="lib/otherlibs/google/protobuf/internal/more_messages_pb2.py" />
        <File name="more_messages_pb2" src="lib/otherlibs/google/protobuf/internal/more_messages_pb2.pyc" />
        <File name="packed_field_test_pb2" src="lib/otherlibs/google/protobuf/internal/packed_field_test_pb2.py" />
        <File name="packed_field_test_pb2" src="lib/otherlibs/google/protobuf/internal/packed_field_test_pb2.pyc" />
        <File name="proto_builder_test" src="lib/otherlibs/google/protobuf/internal/proto_builder_test.py" />
        <File name="proto_builder_test" src="lib/otherlibs/google/protobuf/internal/proto_builder_test.pyc" />
        <File name="python_message" src="lib/otherlibs/google/protobuf/internal/python_message.py" />
        <File name="python_message" src="lib/otherlibs/google/protobuf/internal/python_message.pyc" />
        <File name="reflection_test" src="lib/otherlibs/google/protobuf/internal/reflection_test.py" />
        <File name="reflection_test" src="lib/otherlibs/google/protobuf/internal/reflection_test.pyc" />
        <File name="service_reflection_test" src="lib/otherlibs/google/protobuf/internal/service_reflection_test.py" />
        <File name="service_reflection_test" src="lib/otherlibs/google/protobuf/internal/service_reflection_test.pyc" />
        <File name="symbol_database_test" src="lib/otherlibs/google/protobuf/internal/symbol_database_test.py" />
        <File name="symbol_database_test" src="lib/otherlibs/google/protobuf/internal/symbol_database_test.pyc" />
        <File name="test_bad_identifiers_pb2" src="lib/otherlibs/google/protobuf/internal/test_bad_identifiers_pb2.py" />
        <File name="test_bad_identifiers_pb2" src="lib/otherlibs/google/protobuf/internal/test_bad_identifiers_pb2.pyc" />
        <File name="test_util" src="lib/otherlibs/google/protobuf/internal/test_util.py" />
        <File name="test_util" src="lib/otherlibs/google/protobuf/internal/test_util.pyc" />
        <File name="testing_refleaks" src="lib/otherlibs/google/protobuf/internal/testing_refleaks.py" />
        <File name="testing_refleaks" src="lib/otherlibs/google/protobuf/internal/testing_refleaks.pyc" />
        <File name="text_encoding_test" src="lib/otherlibs/google/protobuf/internal/text_encoding_test.py" />
        <File name="text_encoding_test" src="lib/otherlibs/google/protobuf/internal/text_encoding_test.pyc" />
        <File name="text_format_test" src="lib/otherlibs/google/protobuf/internal/text_format_test.py" />
        <File name="text_format_test" src="lib/otherlibs/google/protobuf/internal/text_format_test.pyc" />
        <File name="type_checkers" src="lib/otherlibs/google/protobuf/internal/type_checkers.py" />
        <File name="type_checkers" src="lib/otherlibs/google/protobuf/internal/type_checkers.pyc" />
        <File name="unknown_fields_test" src="lib/otherlibs/google/protobuf/internal/unknown_fields_test.py" />
        <File name="unknown_fields_test" src="lib/otherlibs/google/protobuf/internal/unknown_fields_test.pyc" />
        <File name="well_known_types" src="lib/otherlibs/google/protobuf/internal/well_known_types.py" />
        <File name="well_known_types" src="lib/otherlibs/google/protobuf/internal/well_known_types.pyc" />
        <File name="well_known_types_test" src="lib/otherlibs/google/protobuf/internal/well_known_types_test.py" />
        <File name="well_known_types_test" src="lib/otherlibs/google/protobuf/internal/well_known_types_test.pyc" />
        <File name="wire_format" src="lib/otherlibs/google/protobuf/internal/wire_format.py" />
        <File name="wire_format" src="lib/otherlibs/google/protobuf/internal/wire_format.pyc" />
        <File name="wire_format_test" src="lib/otherlibs/google/protobuf/internal/wire_format_test.py" />
        <File name="wire_format_test" src="lib/otherlibs/google/protobuf/internal/wire_format_test.pyc" />
        <File name="json_format" src="lib/otherlibs/google/protobuf/json_format.py" />
        <File name="json_format" src="lib/otherlibs/google/protobuf/json_format.pyc" />
        <File name="map_proto2_unittest_pb2" src="lib/otherlibs/google/protobuf/map_proto2_unittest_pb2.py" />
        <File name="map_proto2_unittest_pb2" src="lib/otherlibs/google/protobuf/map_proto2_unittest_pb2.pyc" />
        <File name="map_unittest_pb2" src="lib/otherlibs/google/protobuf/map_unittest_pb2.py" />
        <File name="map_unittest_pb2" src="lib/otherlibs/google/protobuf/map_unittest_pb2.pyc" />
        <File name="message" src="lib/otherlibs/google/protobuf/message.py" />
        <File name="message" src="lib/otherlibs/google/protobuf/message.pyc" />
        <File name="message_factory" src="lib/otherlibs/google/protobuf/message_factory.py" />
        <File name="message_factory" src="lib/otherlibs/google/protobuf/message_factory.pyc" />
        <File name="proto_builder" src="lib/otherlibs/google/protobuf/proto_builder.py" />
        <File name="proto_builder" src="lib/otherlibs/google/protobuf/proto_builder.pyc" />
        <File name="__init__" src="lib/otherlibs/google/protobuf/pyext/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/protobuf/pyext/__init__.pyc" />
        <File name="cpp_message" src="lib/otherlibs/google/protobuf/pyext/cpp_message.py" />
        <File name="cpp_message" src="lib/otherlibs/google/protobuf/pyext/cpp_message.pyc" />
        <File name="python_pb2" src="lib/otherlibs/google/protobuf/pyext/python_pb2.py" />
        <File name="python_pb2" src="lib/otherlibs/google/protobuf/pyext/python_pb2.pyc" />
        <File name="reflection" src="lib/otherlibs/google/protobuf/reflection.py" />
        <File name="reflection" src="lib/otherlibs/google/protobuf/reflection.pyc" />
        <File name="service" src="lib/otherlibs/google/protobuf/service.py" />
        <File name="service" src="lib/otherlibs/google/protobuf/service.pyc" />
        <File name="service_reflection" src="lib/otherlibs/google/protobuf/service_reflection.py" />
        <File name="service_reflection" src="lib/otherlibs/google/protobuf/service_reflection.pyc" />
        <File name="source_context_pb2" src="lib/otherlibs/google/protobuf/source_context_pb2.py" />
        <File name="source_context_pb2" src="lib/otherlibs/google/protobuf/source_context_pb2.pyc" />
        <File name="struct_pb2" src="lib/otherlibs/google/protobuf/struct_pb2.py" />
        <File name="struct_pb2" src="lib/otherlibs/google/protobuf/struct_pb2.pyc" />
        <File name="symbol_database" src="lib/otherlibs/google/protobuf/symbol_database.py" />
        <File name="symbol_database" src="lib/otherlibs/google/protobuf/symbol_database.pyc" />
        <File name="test_messages_proto2_pb2" src="lib/otherlibs/google/protobuf/test_messages_proto2_pb2.py" />
        <File name="test_messages_proto2_pb2" src="lib/otherlibs/google/protobuf/test_messages_proto2_pb2.pyc" />
        <File name="test_messages_proto3_pb2" src="lib/otherlibs/google/protobuf/test_messages_proto3_pb2.py" />
        <File name="test_messages_proto3_pb2" src="lib/otherlibs/google/protobuf/test_messages_proto3_pb2.pyc" />
        <File name="text_encoding" src="lib/otherlibs/google/protobuf/text_encoding.py" />
        <File name="text_encoding" src="lib/otherlibs/google/protobuf/text_encoding.pyc" />
        <File name="text_format" src="lib/otherlibs/google/protobuf/text_format.py" />
        <File name="text_format" src="lib/otherlibs/google/protobuf/text_format.pyc" />
        <File name="timestamp_pb2" src="lib/otherlibs/google/protobuf/timestamp_pb2.py" />
        <File name="timestamp_pb2" src="lib/otherlibs/google/protobuf/timestamp_pb2.pyc" />
        <File name="type_pb2" src="lib/otherlibs/google/protobuf/type_pb2.py" />
        <File name="type_pb2" src="lib/otherlibs/google/protobuf/type_pb2.pyc" />
        <File name="unittest_arena_pb2" src="lib/otherlibs/google/protobuf/unittest_arena_pb2.py" />
        <File name="unittest_arena_pb2" src="lib/otherlibs/google/protobuf/unittest_arena_pb2.pyc" />
        <File name="unittest_custom_options_pb2" src="lib/otherlibs/google/protobuf/unittest_custom_options_pb2.py" />
        <File name="unittest_custom_options_pb2" src="lib/otherlibs/google/protobuf/unittest_custom_options_pb2.pyc" />
        <File name="unittest_import_pb2" src="lib/otherlibs/google/protobuf/unittest_import_pb2.py" />
        <File name="unittest_import_pb2" src="lib/otherlibs/google/protobuf/unittest_import_pb2.pyc" />
        <File name="unittest_import_public_pb2" src="lib/otherlibs/google/protobuf/unittest_import_public_pb2.py" />
        <File name="unittest_import_public_pb2" src="lib/otherlibs/google/protobuf/unittest_import_public_pb2.pyc" />
        <File name="unittest_mset_pb2" src="lib/otherlibs/google/protobuf/unittest_mset_pb2.py" />
        <File name="unittest_mset_pb2" src="lib/otherlibs/google/protobuf/unittest_mset_pb2.pyc" />
        <File name="unittest_mset_wire_format_pb2" src="lib/otherlibs/google/protobuf/unittest_mset_wire_format_pb2.py" />
        <File name="unittest_mset_wire_format_pb2" src="lib/otherlibs/google/protobuf/unittest_mset_wire_format_pb2.pyc" />
        <File name="unittest_no_arena_import_pb2" src="lib/otherlibs/google/protobuf/unittest_no_arena_import_pb2.py" />
        <File name="unittest_no_arena_import_pb2" src="lib/otherlibs/google/protobuf/unittest_no_arena_import_pb2.pyc" />
        <File name="unittest_no_arena_pb2" src="lib/otherlibs/google/protobuf/unittest_no_arena_pb2.py" />
        <File name="unittest_no_arena_pb2" src="lib/otherlibs/google/protobuf/unittest_no_arena_pb2.pyc" />
        <File name="unittest_no_generic_services_pb2" src="lib/otherlibs/google/protobuf/unittest_no_generic_services_pb2.py" />
        <File name="unittest_no_generic_services_pb2" src="lib/otherlibs/google/protobuf/unittest_no_generic_services_pb2.pyc" />
        <File name="unittest_pb2" src="lib/otherlibs/google/protobuf/unittest_pb2.py" />
        <File name="unittest_pb2" src="lib/otherlibs/google/protobuf/unittest_pb2.pyc" />
        <File name="unittest_proto3_arena_pb2" src="lib/otherlibs/google/protobuf/unittest_proto3_arena_pb2.py" />
        <File name="unittest_proto3_arena_pb2" src="lib/otherlibs/google/protobuf/unittest_proto3_arena_pb2.pyc" />
        <File name="__init__" src="lib/otherlibs/google/protobuf/util/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/protobuf/util/__init__.pyc" />
        <File name="json_format_proto3_pb2" src="lib/otherlibs/google/protobuf/util/json_format_proto3_pb2.py" />
        <File name="json_format_proto3_pb2" src="lib/otherlibs/google/protobuf/util/json_format_proto3_pb2.pyc" />
        <File name="wrappers_pb2" src="lib/otherlibs/google/protobuf/wrappers_pb2.py" />
        <File name="wrappers_pb2" src="lib/otherlibs/google/protobuf/wrappers_pb2.pyc" />
        <File name="__init__" src="lib/otherlibs/google/rpc/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/rpc/__init__.pyc" />
        <File name="code_pb2" src="lib/otherlibs/google/rpc/code_pb2.py" />
        <File name="code_pb2" src="lib/otherlibs/google/rpc/code_pb2.pyc" />
        <File name="error_details_pb2" src="lib/otherlibs/google/rpc/error_details_pb2.py" />
        <File name="error_details_pb2" src="lib/otherlibs/google/rpc/error_details_pb2.pyc" />
        <File name="status_pb2" src="lib/otherlibs/google/rpc/status_pb2.py" />
        <File name="status_pb2" src="lib/otherlibs/google/rpc/status_pb2.pyc" />
        <File name="__init__" src="lib/otherlibs/google/type/__init__.py" />
        <File name="__init__" src="lib/otherlibs/google/type/__init__.pyc" />
        <File name="color_pb2" src="lib/otherlibs/google/type/color_pb2.py" />
        <File name="color_pb2" src="lib/otherlibs/google/type/color_pb2.pyc" />
        <File name="date_pb2" src="lib/otherlibs/google/type/date_pb2.py" />
        <File name="date_pb2" src="lib/otherlibs/google/type/date_pb2.pyc" />
        <File name="dayofweek_pb2" src="lib/otherlibs/google/type/dayofweek_pb2.py" />
        <File name="dayofweek_pb2" src="lib/otherlibs/google/type/dayofweek_pb2.pyc" />
        <File name="latlng_pb2" src="lib/otherlibs/google/type/latlng_pb2.py" />
        <File name="latlng_pb2" src="lib/otherlibs/google/type/latlng_pb2.pyc" />
        <File name="money_pb2" src="lib/otherlibs/google/type/money_pb2.py" />
        <File name="money_pb2" src="lib/otherlibs/google/type/money_pb2.pyc" />
        <File name="timeofday_pb2" src="lib/otherlibs/google/type/timeofday_pb2.py" />
        <File name="timeofday_pb2" src="lib/otherlibs/google/type/timeofday_pb2.pyc" />
        <File name="DESCRIPTION" src="lib/otherlibs/google_api_core-0.1.4.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/google_api_core-0.1.4.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/google_api_core-0.1.4.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/google_api_core-0.1.4.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/google_api_core-0.1.4.dist-info/WHEEL" />
        <File name="metadata" src="lib/otherlibs/google_api_core-0.1.4.dist-info/metadata.json" />
        <File name="namespace_packages" src="lib/otherlibs/google_api_core-0.1.4.dist-info/namespace_packages.txt" />
        <File name="top_level" src="lib/otherlibs/google_api_core-0.1.4.dist-info/top_level.txt" />
        <File name="DESCRIPTION" src="lib/otherlibs/google_api_python_client-1.6.5.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/google_api_python_client-1.6.5.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/google_api_python_client-1.6.5.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/google_api_python_client-1.6.5.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/google_api_python_client-1.6.5.dist-info/WHEEL" />
        <File name="metadata" src="lib/otherlibs/google_api_python_client-1.6.5.dist-info/metadata.json" />
        <File name="top_level" src="lib/otherlibs/google_api_python_client-1.6.5.dist-info/top_level.txt" />
        <File name="DESCRIPTION" src="lib/otherlibs/google_auth-1.3.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/google_auth-1.3.0.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/google_auth-1.3.0.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/google_auth-1.3.0.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/google_auth-1.3.0.dist-info/WHEEL" />
        <File name="metadata" src="lib/otherlibs/google_auth-1.3.0.dist-info/metadata.json" />
        <File name="namespace_packages" src="lib/otherlibs/google_auth-1.3.0.dist-info/namespace_packages.txt" />
        <File name="top_level" src="lib/otherlibs/google_auth-1.3.0.dist-info/top_level.txt" />
        <File name="DESCRIPTION" src="lib/otherlibs/google_cloud_speech-0.31.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/google_cloud_speech-0.31.0.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/google_cloud_speech-0.31.0.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/google_cloud_speech-0.31.0.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/google_cloud_speech-0.31.0.dist-info/WHEEL" />
        <File name="metadata" src="lib/otherlibs/google_cloud_speech-0.31.0.dist-info/metadata.json" />
        <File name="namespace_packages" src="lib/otherlibs/google_cloud_speech-0.31.0.dist-info/namespace_packages.txt" />
        <File name="top_level" src="lib/otherlibs/google_cloud_speech-0.31.0.dist-info/top_level.txt" />
        <File name="__init__" src="lib/otherlibs/googleapiclient/__init__.py" />
        <File name="__init__" src="lib/otherlibs/googleapiclient/__init__.pyc" />
        <File name="_auth" src="lib/otherlibs/googleapiclient/_auth.py" />
        <File name="_auth" src="lib/otherlibs/googleapiclient/_auth.pyc" />
        <File name="channel" src="lib/otherlibs/googleapiclient/channel.py" />
        <File name="channel" src="lib/otherlibs/googleapiclient/channel.pyc" />
        <File name="discovery" src="lib/otherlibs/googleapiclient/discovery.py" />
        <File name="discovery" src="lib/otherlibs/googleapiclient/discovery.pyc" />
        <File name="__init__" src="lib/otherlibs/googleapiclient/discovery_cache/__init__.py" />
        <File name="__init__" src="lib/otherlibs/googleapiclient/discovery_cache/__init__.pyc" />
        <File name="appengine_memcache" src="lib/otherlibs/googleapiclient/discovery_cache/appengine_memcache.py" />
        <File name="appengine_memcache" src="lib/otherlibs/googleapiclient/discovery_cache/appengine_memcache.pyc" />
        <File name="base" src="lib/otherlibs/googleapiclient/discovery_cache/base.py" />
        <File name="base" src="lib/otherlibs/googleapiclient/discovery_cache/base.pyc" />
        <File name="file_cache" src="lib/otherlibs/googleapiclient/discovery_cache/file_cache.py" />
        <File name="file_cache" src="lib/otherlibs/googleapiclient/discovery_cache/file_cache.pyc" />
        <File name="errors" src="lib/otherlibs/googleapiclient/errors.py" />
        <File name="errors" src="lib/otherlibs/googleapiclient/errors.pyc" />
        <File name="http" src="lib/otherlibs/googleapiclient/http.py" />
        <File name="http" src="lib/otherlibs/googleapiclient/http.pyc" />
        <File name="mimeparse" src="lib/otherlibs/googleapiclient/mimeparse.py" />
        <File name="mimeparse" src="lib/otherlibs/googleapiclient/mimeparse.pyc" />
        <File name="model" src="lib/otherlibs/googleapiclient/model.py" />
        <File name="model" src="lib/otherlibs/googleapiclient/model.pyc" />
        <File name="sample_tools" src="lib/otherlibs/googleapiclient/sample_tools.py" />
        <File name="sample_tools" src="lib/otherlibs/googleapiclient/sample_tools.pyc" />
        <File name="schema" src="lib/otherlibs/googleapiclient/schema.py" />
        <File name="schema" src="lib/otherlibs/googleapiclient/schema.pyc" />
        <File name="DESCRIPTION" src="lib/otherlibs/googleapis_common_protos-1.5.3.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/googleapis_common_protos-1.5.3.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/googleapis_common_protos-1.5.3.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/googleapis_common_protos-1.5.3.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/googleapis_common_protos-1.5.3.dist-info/WHEEL" />
        <File name="metadata" src="lib/otherlibs/googleapis_common_protos-1.5.3.dist-info/metadata.json" />
        <File name="namespace_packages" src="lib/otherlibs/googleapis_common_protos-1.5.3.dist-info/namespace_packages.txt" />
        <File name="top_level" src="lib/otherlibs/googleapis_common_protos-1.5.3.dist-info/top_level.txt" />
        <File name="DESCRIPTION" src="lib/otherlibs/httplib2-0.10.3.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/httplib2-0.10.3.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/httplib2-0.10.3.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/httplib2-0.10.3.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/httplib2-0.10.3.dist-info/WHEEL" />
        <File name="metadata" src="lib/otherlibs/httplib2-0.10.3.dist-info/metadata.json" />
        <File name="top_level" src="lib/otherlibs/httplib2-0.10.3.dist-info/top_level.txt" />
        <File name="__init__" src="lib/otherlibs/httplib2/__init__.py" />
        <File name="__init__" src="lib/otherlibs/httplib2/__init__.pyc" />
        <File name="cacerts" src="lib/otherlibs/httplib2/cacerts.txt" />
        <File name="iri2uri" src="lib/otherlibs/httplib2/iri2uri.py" />
        <File name="iri2uri" src="lib/otherlibs/httplib2/iri2uri.pyc" />
        <File name="socks" src="lib/otherlibs/httplib2/socks.py" />
        <File name="socks" src="lib/otherlibs/httplib2/socks.pyc" />
        <File name="DESCRIPTION" src="lib/otherlibs/oauth2client-4.1.2.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/oauth2client-4.1.2.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/oauth2client-4.1.2.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/oauth2client-4.1.2.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/oauth2client-4.1.2.dist-info/WHEEL" />
        <File name="metadata" src="lib/otherlibs/oauth2client-4.1.2.dist-info/metadata.json" />
        <File name="top_level" src="lib/otherlibs/oauth2client-4.1.2.dist-info/top_level.txt" />
        <File name="DESCRIPTION" src="lib/otherlibs/pyasn1-0.4.2.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/pyasn1-0.4.2.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/pyasn1-0.4.2.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/pyasn1-0.4.2.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/pyasn1-0.4.2.dist-info/WHEEL" />
        <File name="metadata" src="lib/otherlibs/pyasn1-0.4.2.dist-info/metadata.json" />
        <File name="top_level" src="lib/otherlibs/pyasn1-0.4.2.dist-info/top_level.txt" />
        <File name="zip-safe" src="lib/otherlibs/pyasn1-0.4.2.dist-info/zip-safe" />
        <File name="__init__" src="lib/otherlibs/pyasn1/__init__.py" />
        <File name="__init__" src="lib/otherlibs/pyasn1/__init__.pyc" />
        <File name="__init__" src="lib/otherlibs/pyasn1/codec/__init__.py" />
        <File name="__init__" src="lib/otherlibs/pyasn1/codec/__init__.pyc" />
        <File name="__init__" src="lib/otherlibs/pyasn1/codec/ber/__init__.py" />
        <File name="__init__" src="lib/otherlibs/pyasn1/codec/ber/__init__.pyc" />
        <File name="decoder" src="lib/otherlibs/pyasn1/codec/ber/decoder.py" />
        <File name="decoder" src="lib/otherlibs/pyasn1/codec/ber/decoder.pyc" />
        <File name="encoder" src="lib/otherlibs/pyasn1/codec/ber/encoder.py" />
        <File name="encoder" src="lib/otherlibs/pyasn1/codec/ber/encoder.pyc" />
        <File name="eoo" src="lib/otherlibs/pyasn1/codec/ber/eoo.py" />
        <File name="eoo" src="lib/otherlibs/pyasn1/codec/ber/eoo.pyc" />
        <File name="__init__" src="lib/otherlibs/pyasn1/codec/cer/__init__.py" />
        <File name="__init__" src="lib/otherlibs/pyasn1/codec/cer/__init__.pyc" />
        <File name="decoder" src="lib/otherlibs/pyasn1/codec/cer/decoder.py" />
        <File name="decoder" src="lib/otherlibs/pyasn1/codec/cer/decoder.pyc" />
        <File name="encoder" src="lib/otherlibs/pyasn1/codec/cer/encoder.py" />
        <File name="encoder" src="lib/otherlibs/pyasn1/codec/cer/encoder.pyc" />
        <File name="__init__" src="lib/otherlibs/pyasn1/codec/der/__init__.py" />
        <File name="__init__" src="lib/otherlibs/pyasn1/codec/der/__init__.pyc" />
        <File name="decoder" src="lib/otherlibs/pyasn1/codec/der/decoder.py" />
        <File name="decoder" src="lib/otherlibs/pyasn1/codec/der/decoder.pyc" />
        <File name="encoder" src="lib/otherlibs/pyasn1/codec/der/encoder.py" />
        <File name="encoder" src="lib/otherlibs/pyasn1/codec/der/encoder.pyc" />
        <File name="__init__" src="lib/otherlibs/pyasn1/codec/native/__init__.py" />
        <File name="__init__" src="lib/otherlibs/pyasn1/codec/native/__init__.pyc" />
        <File name="decoder" src="lib/otherlibs/pyasn1/codec/native/decoder.py" />
        <File name="decoder" src="lib/otherlibs/pyasn1/codec/native/decoder.pyc" />
        <File name="encoder" src="lib/otherlibs/pyasn1/codec/native/encoder.py" />
        <File name="encoder" src="lib/otherlibs/pyasn1/codec/native/encoder.pyc" />
        <File name="__init__" src="lib/otherlibs/pyasn1/compat/__init__.py" />
        <File name="__init__" src="lib/otherlibs/pyasn1/compat/__init__.pyc" />
        <File name="binary" src="lib/otherlibs/pyasn1/compat/binary.py" />
        <File name="binary" src="lib/otherlibs/pyasn1/compat/binary.pyc" />
        <File name="calling" src="lib/otherlibs/pyasn1/compat/calling.py" />
        <File name="calling" src="lib/otherlibs/pyasn1/compat/calling.pyc" />
        <File name="dateandtime" src="lib/otherlibs/pyasn1/compat/dateandtime.py" />
        <File name="dateandtime" src="lib/otherlibs/pyasn1/compat/dateandtime.pyc" />
        <File name="integer" src="lib/otherlibs/pyasn1/compat/integer.py" />
        <File name="integer" src="lib/otherlibs/pyasn1/compat/integer.pyc" />
        <File name="octets" src="lib/otherlibs/pyasn1/compat/octets.py" />
        <File name="octets" src="lib/otherlibs/pyasn1/compat/octets.pyc" />
        <File name="string" src="lib/otherlibs/pyasn1/compat/string.py" />
        <File name="string" src="lib/otherlibs/pyasn1/compat/string.pyc" />
        <File name="debug" src="lib/otherlibs/pyasn1/debug.py" />
        <File name="debug" src="lib/otherlibs/pyasn1/debug.pyc" />
        <File name="error" src="lib/otherlibs/pyasn1/error.py" />
        <File name="error" src="lib/otherlibs/pyasn1/error.pyc" />
        <File name="__init__" src="lib/otherlibs/pyasn1/type/__init__.py" />
        <File name="__init__" src="lib/otherlibs/pyasn1/type/__init__.pyc" />
        <File name="base" src="lib/otherlibs/pyasn1/type/base.py" />
        <File name="base" src="lib/otherlibs/pyasn1/type/base.pyc" />
        <File name="char" src="lib/otherlibs/pyasn1/type/char.py" />
        <File name="char" src="lib/otherlibs/pyasn1/type/char.pyc" />
        <File name="constraint" src="lib/otherlibs/pyasn1/type/constraint.py" />
        <File name="constraint" src="lib/otherlibs/pyasn1/type/constraint.pyc" />
        <File name="error" src="lib/otherlibs/pyasn1/type/error.py" />
        <File name="error" src="lib/otherlibs/pyasn1/type/error.pyc" />
        <File name="namedtype" src="lib/otherlibs/pyasn1/type/namedtype.py" />
        <File name="namedtype" src="lib/otherlibs/pyasn1/type/namedtype.pyc" />
        <File name="namedval" src="lib/otherlibs/pyasn1/type/namedval.py" />
        <File name="namedval" src="lib/otherlibs/pyasn1/type/namedval.pyc" />
        <File name="opentype" src="lib/otherlibs/pyasn1/type/opentype.py" />
        <File name="opentype" src="lib/otherlibs/pyasn1/type/opentype.pyc" />
        <File name="tag" src="lib/otherlibs/pyasn1/type/tag.py" />
        <File name="tag" src="lib/otherlibs/pyasn1/type/tag.pyc" />
        <File name="tagmap" src="lib/otherlibs/pyasn1/type/tagmap.py" />
        <File name="tagmap" src="lib/otherlibs/pyasn1/type/tagmap.pyc" />
        <File name="univ" src="lib/otherlibs/pyasn1/type/univ.py" />
        <File name="univ" src="lib/otherlibs/pyasn1/type/univ.pyc" />
        <File name="useful" src="lib/otherlibs/pyasn1/type/useful.py" />
        <File name="useful" src="lib/otherlibs/pyasn1/type/useful.pyc" />
        <File name="DESCRIPTION" src="lib/otherlibs/pyasn1_modules-0.2.1.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/pyasn1_modules-0.2.1.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/pyasn1_modules-0.2.1.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/pyasn1_modules-0.2.1.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/pyasn1_modules-0.2.1.dist-info/WHEEL" />
        <File name="metadata" src="lib/otherlibs/pyasn1_modules-0.2.1.dist-info/metadata.json" />
        <File name="top_level" src="lib/otherlibs/pyasn1_modules-0.2.1.dist-info/top_level.txt" />
        <File name="zip-safe" src="lib/otherlibs/pyasn1_modules-0.2.1.dist-info/zip-safe" />
        <File name="__init__" src="lib/otherlibs/pyasn1_modules/__init__.py" />
        <File name="__init__" src="lib/otherlibs/pyasn1_modules/__init__.pyc" />
        <File name="pem" src="lib/otherlibs/pyasn1_modules/pem.py" />
        <File name="pem" src="lib/otherlibs/pyasn1_modules/pem.pyc" />
        <File name="rfc1155" src="lib/otherlibs/pyasn1_modules/rfc1155.py" />
        <File name="rfc1155" src="lib/otherlibs/pyasn1_modules/rfc1155.pyc" />
        <File name="rfc1157" src="lib/otherlibs/pyasn1_modules/rfc1157.py" />
        <File name="rfc1157" src="lib/otherlibs/pyasn1_modules/rfc1157.pyc" />
        <File name="rfc1901" src="lib/otherlibs/pyasn1_modules/rfc1901.py" />
        <File name="rfc1901" src="lib/otherlibs/pyasn1_modules/rfc1901.pyc" />
        <File name="rfc1902" src="lib/otherlibs/pyasn1_modules/rfc1902.py" />
        <File name="rfc1902" src="lib/otherlibs/pyasn1_modules/rfc1902.pyc" />
        <File name="rfc1905" src="lib/otherlibs/pyasn1_modules/rfc1905.py" />
        <File name="rfc1905" src="lib/otherlibs/pyasn1_modules/rfc1905.pyc" />
        <File name="rfc2251" src="lib/otherlibs/pyasn1_modules/rfc2251.py" />
        <File name="rfc2251" src="lib/otherlibs/pyasn1_modules/rfc2251.pyc" />
        <File name="rfc2314" src="lib/otherlibs/pyasn1_modules/rfc2314.py" />
        <File name="rfc2314" src="lib/otherlibs/pyasn1_modules/rfc2314.pyc" />
        <File name="rfc2315" src="lib/otherlibs/pyasn1_modules/rfc2315.py" />
        <File name="rfc2315" src="lib/otherlibs/pyasn1_modules/rfc2315.pyc" />
        <File name="rfc2437" src="lib/otherlibs/pyasn1_modules/rfc2437.py" />
        <File name="rfc2437" src="lib/otherlibs/pyasn1_modules/rfc2437.pyc" />
        <File name="rfc2459" src="lib/otherlibs/pyasn1_modules/rfc2459.py" />
        <File name="rfc2459" src="lib/otherlibs/pyasn1_modules/rfc2459.pyc" />
        <File name="rfc2511" src="lib/otherlibs/pyasn1_modules/rfc2511.py" />
        <File name="rfc2511" src="lib/otherlibs/pyasn1_modules/rfc2511.pyc" />
        <File name="rfc2560" src="lib/otherlibs/pyasn1_modules/rfc2560.py" />
        <File name="rfc2560" src="lib/otherlibs/pyasn1_modules/rfc2560.pyc" />
        <File name="rfc3279" src="lib/otherlibs/pyasn1_modules/rfc3279.py" />
        <File name="rfc3279" src="lib/otherlibs/pyasn1_modules/rfc3279.pyc" />
        <File name="rfc3280" src="lib/otherlibs/pyasn1_modules/rfc3280.py" />
        <File name="rfc3280" src="lib/otherlibs/pyasn1_modules/rfc3280.pyc" />
        <File name="rfc3281" src="lib/otherlibs/pyasn1_modules/rfc3281.py" />
        <File name="rfc3281" src="lib/otherlibs/pyasn1_modules/rfc3281.pyc" />
        <File name="rfc3412" src="lib/otherlibs/pyasn1_modules/rfc3412.py" />
        <File name="rfc3412" src="lib/otherlibs/pyasn1_modules/rfc3412.pyc" />
        <File name="rfc3414" src="lib/otherlibs/pyasn1_modules/rfc3414.py" />
        <File name="rfc3414" src="lib/otherlibs/pyasn1_modules/rfc3414.pyc" />
        <File name="rfc3447" src="lib/otherlibs/pyasn1_modules/rfc3447.py" />
        <File name="rfc3447" src="lib/otherlibs/pyasn1_modules/rfc3447.pyc" />
        <File name="rfc3852" src="lib/otherlibs/pyasn1_modules/rfc3852.py" />
        <File name="rfc3852" src="lib/otherlibs/pyasn1_modules/rfc3852.pyc" />
        <File name="rfc4210" src="lib/otherlibs/pyasn1_modules/rfc4210.py" />
        <File name="rfc4210" src="lib/otherlibs/pyasn1_modules/rfc4210.pyc" />
        <File name="rfc4211" src="lib/otherlibs/pyasn1_modules/rfc4211.py" />
        <File name="rfc4211" src="lib/otherlibs/pyasn1_modules/rfc4211.pyc" />
        <File name="rfc5208" src="lib/otherlibs/pyasn1_modules/rfc5208.py" />
        <File name="rfc5208" src="lib/otherlibs/pyasn1_modules/rfc5208.pyc" />
        <File name="rfc5280" src="lib/otherlibs/pyasn1_modules/rfc5280.py" />
        <File name="rfc5280" src="lib/otherlibs/pyasn1_modules/rfc5280.pyc" />
        <File name="rfc5652" src="lib/otherlibs/pyasn1_modules/rfc5652.py" />
        <File name="rfc5652" src="lib/otherlibs/pyasn1_modules/rfc5652.pyc" />
        <File name="rfc6402" src="lib/otherlibs/pyasn1_modules/rfc6402.py" />
        <File name="rfc6402" src="lib/otherlibs/pyasn1_modules/rfc6402.pyc" />
        <File name="DESCRIPTION" src="lib/otherlibs/rsa-3.4.2.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/rsa-3.4.2.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/rsa-3.4.2.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/rsa-3.4.2.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/rsa-3.4.2.dist-info/WHEEL" />
        <File name="entry_points" src="lib/otherlibs/rsa-3.4.2.dist-info/entry_points.txt" />
        <File name="metadata" src="lib/otherlibs/rsa-3.4.2.dist-info/metadata.json" />
        <File name="top_level" src="lib/otherlibs/rsa-3.4.2.dist-info/top_level.txt" />
        <File name="__init__" src="lib/otherlibs/rsa/__init__.py" />
        <File name="__init__" src="lib/otherlibs/rsa/__init__.pyc" />
        <File name="_compat" src="lib/otherlibs/rsa/_compat.py" />
        <File name="_compat" src="lib/otherlibs/rsa/_compat.pyc" />
        <File name="_version133" src="lib/otherlibs/rsa/_version133.py" />
        <File name="_version133" src="lib/otherlibs/rsa/_version133.pyc" />
        <File name="_version200" src="lib/otherlibs/rsa/_version200.py" />
        <File name="_version200" src="lib/otherlibs/rsa/_version200.pyc" />
        <File name="asn1" src="lib/otherlibs/rsa/asn1.py" />
        <File name="asn1" src="lib/otherlibs/rsa/asn1.pyc" />
        <File name="bigfile" src="lib/otherlibs/rsa/bigfile.py" />
        <File name="bigfile" src="lib/otherlibs/rsa/bigfile.pyc" />
        <File name="cli" src="lib/otherlibs/rsa/cli.py" />
        <File name="cli" src="lib/otherlibs/rsa/cli.pyc" />
        <File name="common" src="lib/otherlibs/rsa/common.py" />
        <File name="common" src="lib/otherlibs/rsa/common.pyc" />
        <File name="core" src="lib/otherlibs/rsa/core.py" />
        <File name="core" src="lib/otherlibs/rsa/core.pyc" />
        <File name="key" src="lib/otherlibs/rsa/key.py" />
        <File name="key" src="lib/otherlibs/rsa/key.pyc" />
        <File name="parallel" src="lib/otherlibs/rsa/parallel.py" />
        <File name="parallel" src="lib/otherlibs/rsa/parallel.pyc" />
        <File name="pem" src="lib/otherlibs/rsa/pem.py" />
        <File name="pem" src="lib/otherlibs/rsa/pem.pyc" />
        <File name="pkcs1" src="lib/otherlibs/rsa/pkcs1.py" />
        <File name="pkcs1" src="lib/otherlibs/rsa/pkcs1.pyc" />
        <File name="prime" src="lib/otherlibs/rsa/prime.py" />
        <File name="prime" src="lib/otherlibs/rsa/prime.pyc" />
        <File name="randnum" src="lib/otherlibs/rsa/randnum.py" />
        <File name="randnum" src="lib/otherlibs/rsa/randnum.pyc" />
        <File name="transform" src="lib/otherlibs/rsa/transform.py" />
        <File name="transform" src="lib/otherlibs/rsa/transform.pyc" />
        <File name="util" src="lib/otherlibs/rsa/util.py" />
        <File name="util" src="lib/otherlibs/rsa/util.pyc" />
        <File name="varblock" src="lib/otherlibs/rsa/varblock.py" />
        <File name="varblock" src="lib/otherlibs/rsa/varblock.pyc" />
        <File name="DESCRIPTION" src="lib/otherlibs/six-1.11.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/six-1.11.0.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/six-1.11.0.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/six-1.11.0.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/six-1.11.0.dist-info/WHEEL" />
        <File name="metadata" src="lib/otherlibs/six-1.11.0.dist-info/metadata.json" />
        <File name="top_level" src="lib/otherlibs/six-1.11.0.dist-info/top_level.txt" />
        <File name="six" src="lib/otherlibs/six.py" />
        <File name="__init__" src="lib/otherlibs/six/__init__.pyi" />
        <File name="__init__" src="lib/otherlibs/six/moves/__init__.pyi" />
        <File name="cPickle" src="lib/otherlibs/six/moves/cPickle.pyi" />
        <File name="__init__" src="lib/otherlibs/six/moves/urllib/__init__.pyi" />
        <File name="error" src="lib/otherlibs/six/moves/urllib/error.pyi" />
        <File name="parse" src="lib/otherlibs/six/moves/urllib/parse.pyi" />
        <File name="request" src="lib/otherlibs/six/moves/urllib/request.pyi" />
        <File name="response" src="lib/otherlibs/six/moves/urllib/response.pyi" />
        <File name="robotparser" src="lib/otherlibs/six/moves/urllib/robotparser.pyi" />
        <File name="urllib_error" src="lib/otherlibs/six/moves/urllib_error.pyi" />
        <File name="urllib_parse" src="lib/otherlibs/six/moves/urllib_parse.pyi" />
        <File name="urllib_request" src="lib/otherlibs/six/moves/urllib_request.pyi" />
        <File name="urllib_response" src="lib/otherlibs/six/moves/urllib_response.pyi" />
        <File name="urllib_robotparser" src="lib/otherlibs/six/moves/urllib_robotparser.pyi" />
        <File name="DESCRIPTION" src="lib/otherlibs/uritemplate-3.0.0.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/uritemplate-3.0.0.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/uritemplate-3.0.0.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/uritemplate-3.0.0.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/uritemplate-3.0.0.dist-info/WHEEL" />
        <File name="metadata" src="lib/otherlibs/uritemplate-3.0.0.dist-info/metadata.json" />
        <File name="top_level" src="lib/otherlibs/uritemplate-3.0.0.dist-info/top_level.txt" />
        <File name="__init__" src="lib/otherlibs/uritemplate/__init__.py" />
        <File name="__init__" src="lib/otherlibs/uritemplate/__init__.pyc" />
        <File name="api" src="lib/otherlibs/uritemplate/api.py" />
        <File name="api" src="lib/otherlibs/uritemplate/api.pyc" />
        <File name="template" src="lib/otherlibs/uritemplate/template.py" />
        <File name="template" src="lib/otherlibs/uritemplate/template.pyc" />
        <File name="variable" src="lib/otherlibs/uritemplate/variable.py" />
        <File name="variable" src="lib/otherlibs/uritemplate/variable.pyc" />
        <File name="DESCRIPTION" src="lib/otherlibs/urllib3-1.22.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/urllib3-1.22.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/urllib3-1.22.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/urllib3-1.22.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/urllib3-1.22.dist-info/WHEEL" />
        <File name="metadata" src="lib/otherlibs/urllib3-1.22.dist-info/metadata.json" />
        <File name="top_level" src="lib/otherlibs/urllib3-1.22.dist-info/top_level.txt" />
        <File name="__init__" src="lib/otherlibs/urllib3/__init__.py" />
        <File name="__init__" src="lib/otherlibs/urllib3/__init__.pyc" />
        <File name="_collections" src="lib/otherlibs/urllib3/_collections.py" />
        <File name="_collections" src="lib/otherlibs/urllib3/_collections.pyc" />
        <File name="connection" src="lib/otherlibs/urllib3/connection.py" />
        <File name="connection" src="lib/otherlibs/urllib3/connection.pyc" />
        <File name="connectionpool" src="lib/otherlibs/urllib3/connectionpool.py" />
        <File name="connectionpool" src="lib/otherlibs/urllib3/connectionpool.pyc" />
        <File name="__init__" src="lib/otherlibs/urllib3/contrib/__init__.py" />
        <File name="__init__" src="lib/otherlibs/urllib3/contrib/__init__.pyc" />
        <File name="__init__" src="lib/otherlibs/urllib3/contrib/_securetransport/__init__.py" />
        <File name="__init__" src="lib/otherlibs/urllib3/contrib/_securetransport/__init__.pyc" />
        <File name="bindings" src="lib/otherlibs/urllib3/contrib/_securetransport/bindings.py" />
        <File name="bindings" src="lib/otherlibs/urllib3/contrib/_securetransport/bindings.pyc" />
        <File name="low_level" src="lib/otherlibs/urllib3/contrib/_securetransport/low_level.py" />
        <File name="low_level" src="lib/otherlibs/urllib3/contrib/_securetransport/low_level.pyc" />
        <File name="appengine" src="lib/otherlibs/urllib3/contrib/appengine.py" />
        <File name="appengine" src="lib/otherlibs/urllib3/contrib/appengine.pyc" />
        <File name="ntlmpool" src="lib/otherlibs/urllib3/contrib/ntlmpool.py" />
        <File name="ntlmpool" src="lib/otherlibs/urllib3/contrib/ntlmpool.pyc" />
        <File name="pyopenssl" src="lib/otherlibs/urllib3/contrib/pyopenssl.py" />
        <File name="pyopenssl" src="lib/otherlibs/urllib3/contrib/pyopenssl.pyc" />
        <File name="securetransport" src="lib/otherlibs/urllib3/contrib/securetransport.py" />
        <File name="securetransport" src="lib/otherlibs/urllib3/contrib/securetransport.pyc" />
        <File name="socks" src="lib/otherlibs/urllib3/contrib/socks.py" />
        <File name="socks" src="lib/otherlibs/urllib3/contrib/socks.pyc" />
        <File name="exceptions" src="lib/otherlibs/urllib3/exceptions.py" />
        <File name="exceptions" src="lib/otherlibs/urllib3/exceptions.pyc" />
        <File name="fields" src="lib/otherlibs/urllib3/fields.py" />
        <File name="fields" src="lib/otherlibs/urllib3/fields.pyc" />
        <File name="filepost" src="lib/otherlibs/urllib3/filepost.py" />
        <File name="filepost" src="lib/otherlibs/urllib3/filepost.pyc" />
        <File name="__init__" src="lib/otherlibs/urllib3/packages/__init__.py" />
        <File name="__init__" src="lib/otherlibs/urllib3/packages/__init__.pyc" />
        <File name="__init__" src="lib/otherlibs/urllib3/packages/backports/__init__.py" />
        <File name="__init__" src="lib/otherlibs/urllib3/packages/backports/__init__.pyc" />
        <File name="makefile" src="lib/otherlibs/urllib3/packages/backports/makefile.py" />
        <File name="makefile" src="lib/otherlibs/urllib3/packages/backports/makefile.pyc" />
        <File name="ordered_dict" src="lib/otherlibs/urllib3/packages/ordered_dict.py" />
        <File name="ordered_dict" src="lib/otherlibs/urllib3/packages/ordered_dict.pyc" />
        <File name="six" src="lib/otherlibs/urllib3/packages/six.py" />
        <File name="six" src="lib/otherlibs/urllib3/packages/six.pyc" />
        <File name="__init__" src="lib/otherlibs/urllib3/packages/ssl_match_hostname/__init__.py" />
        <File name="__init__" src="lib/otherlibs/urllib3/packages/ssl_match_hostname/__init__.pyc" />
        <File name="_implementation" src="lib/otherlibs/urllib3/packages/ssl_match_hostname/_implementation.py" />
        <File name="_implementation" src="lib/otherlibs/urllib3/packages/ssl_match_hostname/_implementation.pyc" />
        <File name="poolmanager" src="lib/otherlibs/urllib3/poolmanager.py" />
        <File name="poolmanager" src="lib/otherlibs/urllib3/poolmanager.pyc" />
        <File name="request" src="lib/otherlibs/urllib3/request.py" />
        <File name="request" src="lib/otherlibs/urllib3/request.pyc" />
        <File name="response" src="lib/otherlibs/urllib3/response.py" />
        <File name="response" src="lib/otherlibs/urllib3/response.pyc" />
        <File name="__init__" src="lib/otherlibs/urllib3/util/__init__.py" />
        <File name="__init__" src="lib/otherlibs/urllib3/util/__init__.pyc" />
        <File name="connection" src="lib/otherlibs/urllib3/util/connection.py" />
        <File name="connection" src="lib/otherlibs/urllib3/util/connection.pyc" />
        <File name="request" src="lib/otherlibs/urllib3/util/request.py" />
        <File name="request" src="lib/otherlibs/urllib3/util/request.pyc" />
        <File name="response" src="lib/otherlibs/urllib3/util/response.py" />
        <File name="response" src="lib/otherlibs/urllib3/util/response.pyc" />
        <File name="retry" src="lib/otherlibs/urllib3/util/retry.py" />
        <File name="retry" src="lib/otherlibs/urllib3/util/retry.pyc" />
        <File name="selectors" src="lib/otherlibs/urllib3/util/selectors.py" />
        <File name="selectors" src="lib/otherlibs/urllib3/util/selectors.pyc" />
        <File name="ssl_" src="lib/otherlibs/urllib3/util/ssl_.py" />
        <File name="ssl_" src="lib/otherlibs/urllib3/util/ssl_.pyc" />
        <File name="timeout" src="lib/otherlibs/urllib3/util/timeout.py" />
        <File name="timeout" src="lib/otherlibs/urllib3/util/timeout.pyc" />
        <File name="url" src="lib/otherlibs/urllib3/util/url.py" />
        <File name="url" src="lib/otherlibs/urllib3/util/url.pyc" />
        <File name="wait" src="lib/otherlibs/urllib3/util/wait.py" />
        <File name="wait" src="lib/otherlibs/urllib3/util/wait.pyc" />
        <File name=".dropbox" src="lib/otherlibs/SpeechRecognition-3.8.1.dist-info/.dropbox.attr" />
        <File name="DESCRIPTION" src="lib/otherlibs/SpeechRecognition-3.8.1.dist-info/DESCRIPTION.rst" />
        <File name="INSTALLER" src="lib/otherlibs/SpeechRecognition-3.8.1.dist-info/INSTALLER" />
        <File name="METADATA" src="lib/otherlibs/SpeechRecognition-3.8.1.dist-info/METADATA" />
        <File name="RECORD" src="lib/otherlibs/SpeechRecognition-3.8.1.dist-info/RECORD" />
        <File name="WHEEL" src="lib/otherlibs/SpeechRecognition-3.8.1.dist-info/WHEEL" />
        <File name="metadata" src="lib/otherlibs/SpeechRecognition-3.8.1.dist-info/metadata.json" />
        <File name="pbr" src="lib/otherlibs/SpeechRecognition-3.8.1.dist-info/pbr.json" />
        <File name="top_level" src="lib/otherlibs/SpeechRecognition-3.8.1.dist-info/top_level.txt" />
        <File name="__init__" src="lib/otherlibs/speech_recognition/__init__.py" />
        <File name="__init__" src="lib/otherlibs/speech_recognition/__init__.pyc" />
        <File name="__main__" src="lib/otherlibs/speech_recognition/__main__.py" />
        <File name="__main__" src="lib/otherlibs/speech_recognition/__main__.pyc" />
        <File name="flac-linux-x86" src="lib/otherlibs/speech_recognition/flac-linux-x86" />
        <File name="flac-linux-x86_64" src="lib/otherlibs/speech_recognition/flac-linux-x86_64" />
        <File name="flac-mac" src="lib/otherlibs/speech_recognition/flac-mac" />
        <File name="flac-win32" src="lib/otherlibs/speech_recognition/flac-win32.exe" />
        <File name="LICENSE" src="lib/otherlibs/speech_recognition/pocketsphinx-data/en-US/LICENSE.txt" />
        <File name="README" src="lib/otherlibs/speech_recognition/pocketsphinx-data/en-US/acoustic-model/README" />
        <File name="feat" src="lib/otherlibs/speech_recognition/pocketsphinx-data/en-US/acoustic-model/feat.params" />
        <File name="mdef" src="lib/otherlibs/speech_recognition/pocketsphinx-data/en-US/acoustic-model/mdef" />
        <File name="means" src="lib/otherlibs/speech_recognition/pocketsphinx-data/en-US/acoustic-model/means" />
        <File name="noisedict" src="lib/otherlibs/speech_recognition/pocketsphinx-data/en-US/acoustic-model/noisedict" />
        <File name="sendump" src="lib/otherlibs/speech_recognition/pocketsphinx-data/en-US/acoustic-model/sendump" />
        <File name="transition_matrices" src="lib/otherlibs/speech_recognition/pocketsphinx-data/en-US/acoustic-model/transition_matrices" />
        <File name="variances" src="lib/otherlibs/speech_recognition/pocketsphinx-data/en-US/acoustic-model/variances" />
        <File name="language-model.lm" src="lib/otherlibs/speech_recognition/pocketsphinx-data/en-US/language-model.lm.bin" />
        <File name="pronounciation-dictionary" src="lib/otherlibs/speech_recognition/pocketsphinx-data/en-US/pronounciation-dictionary.dict" />
    </Resources>
    <Topics />
    <IgnoredPaths>
        <Path src=".idea/misc.xml" />
        <Path src=".idea/inspectionProfiles" />
        <Path src=".idea/workspace.xml" />
        <Path src=".idea" />
        <Path src=".idea/asr2.iml" />
        <Path src=".idea/modules.xml" />
    </IgnoredPaths>
    <qipython name="asr2" />
</Package>
