<?xml version="1.0" encoding="UTF-8" ?>
<Package name="App-DisplayWeatherReport" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="weather-report" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="index" src="html/css/index.css" />
        <File name="standardize" src="html/css/standardize.css" />
        <File name="Droplet" src="html/images/Droplet.svg" />
        <File name="Sun" src="html/images/Sun.svg" />
        <File name="Wind" src="html/images/Wind.svg" />
        <File name="0" src="html/images/weathericons/0.svg" />
        <File name="1" src="html/images/weathericons/1.svg" />
        <File name="10" src="html/images/weathericons/10.svg" />
        <File name="11" src="html/images/weathericons/11.svg" />
        <File name="12" src="html/images/weathericons/12.svg" />
        <File name="13" src="html/images/weathericons/13.svg" />
        <File name="14" src="html/images/weathericons/14.svg" />
        <File name="15" src="html/images/weathericons/15.svg" />
        <File name="16" src="html/images/weathericons/16.svg" />
        <File name="17" src="html/images/weathericons/17.svg" />
        <File name="18" src="html/images/weathericons/18.svg" />
        <File name="19" src="html/images/weathericons/19.svg" />
        <File name="2" src="html/images/weathericons/2.svg" />
        <File name="20" src="html/images/weathericons/20.svg" />
        <File name="21" src="html/images/weathericons/21.svg" />
        <File name="22" src="html/images/weathericons/22.svg" />
        <File name="23" src="html/images/weathericons/23.svg" />
        <File name="24" src="html/images/weathericons/24.svg" />
        <File name="25" src="html/images/weathericons/25.svg" />
        <File name="26" src="html/images/weathericons/26.svg" />
        <File name="27" src="html/images/weathericons/27.svg" />
        <File name="28" src="html/images/weathericons/28.svg" />
        <File name="29" src="html/images/weathericons/29.svg" />
        <File name="3" src="html/images/weathericons/3.svg" />
        <File name="30" src="html/images/weathericons/30.svg" />
        <File name="31" src="html/images/weathericons/31.svg" />
        <File name="32" src="html/images/weathericons/32.svg" />
        <File name="3200" src="html/images/weathericons/3200.svg" />
        <File name="33" src="html/images/weathericons/33.svg" />
        <File name="34" src="html/images/weathericons/34.svg" />
        <File name="35" src="html/images/weathericons/35.svg" />
        <File name="36" src="html/images/weathericons/36.svg" />
        <File name="37" src="html/images/weathericons/37.svg" />
        <File name="38" src="html/images/weathericons/38.svg" />
        <File name="39" src="html/images/weathericons/39.svg" />
        <File name="4" src="html/images/weathericons/4.svg" />
        <File name="40" src="html/images/weathericons/40.svg" />
        <File name="41" src="html/images/weathericons/41.svg" />
        <File name="42" src="html/images/weathericons/42.svg" />
        <File name="43" src="html/images/weathericons/43.svg" />
        <File name="44" src="html/images/weathericons/44.svg" />
        <File name="45" src="html/images/weathericons/45.svg" />
        <File name="46" src="html/images/weathericons/46.svg" />
        <File name="47" src="html/images/weathericons/47.svg" />
        <File name="5" src="html/images/weathericons/5.svg" />
        <File name="6" src="html/images/weathericons/6.svg" />
        <File name="7" src="html/images/weathericons/7.svg" />
        <File name="8" src="html/images/weathericons/8.svg" />
        <File name="9" src="html/images/weathericons/9.svg" />
        <File name="Archive" src="html/images/weathericons/Archive.zip" />
        <File name="index" src="html/index.html" />
        <File name="weather" src="html/js/weather.js" />
        <File name="jquery-3.2.1.min" src="html/js/jquery-3.2.1.min.js" />
        <File name="weather-icons.min" src="html/css/weather-icons.min.css" />
        <File name="weathericons-regular-webfont" src="html/font/weathericons-regular-webfont.eot" />
        <File name="weathericons-regular-webfont" src="html/font/weathericons-regular-webfont.svg" />
        <File name="weathericons-regular-webfont" src="html/font/weathericons-regular-webfont.ttf" />
        <File name="weathericons-regular-webfont" src="html/font/weathericons-regular-webfont.woff" />
        <File name="weathericons-regular-webfont" src="html/font/weathericons-regular-webfont.woff2" />
        <File name="classes-beaufort" src="html/less/icon-classes/classes-beaufort.less" />
        <File name="classes-day" src="html/less/icon-classes/classes-day.less" />
        <File name="classes-direction" src="html/less/icon-classes/classes-direction.less" />
        <File name="classes-misc" src="html/less/icon-classes/classes-misc.less" />
        <File name="classes-moon-aliases" src="html/less/icon-classes/classes-moon-aliases.less" />
        <File name="classes-moon" src="html/less/icon-classes/classes-moon.less" />
        <File name="classes-neutral" src="html/less/icon-classes/classes-neutral.less" />
        <File name="classes-night" src="html/less/icon-classes/classes-night.less" />
        <File name="classes-time" src="html/less/icon-classes/classes-time.less" />
        <File name="classes-wind-aliases" src="html/less/icon-classes/classes-wind-aliases.less" />
        <File name="classes-wind-degrees" src="html/less/icon-classes/classes-wind-degrees.less" />
        <File name="classes-wind" src="html/less/icon-classes/classes-wind.less" />
        <File name="variables-beaufort" src="html/less/icon-variables/variables-beaufort.less" />
        <File name="variables-day" src="html/less/icon-variables/variables-day.less" />
        <File name="variables-direction" src="html/less/icon-variables/variables-direction.less" />
        <File name="variables-misc" src="html/less/icon-variables/variables-misc.less" />
        <File name="variables-moon" src="html/less/icon-variables/variables-moon.less" />
        <File name="variables-neutral" src="html/less/icon-variables/variables-neutral.less" />
        <File name="variables-night" src="html/less/icon-variables/variables-night.less" />
        <File name="variables-time" src="html/less/icon-variables/variables-time.less" />
        <File name="variables-wind-names" src="html/less/icon-variables/variables-wind-names.less" />
        <File name="wi-forecast-io" src="html/less/mappings/wi-forecast-io.less" />
        <File name="wi-owm" src="html/less/mappings/wi-owm.less" />
        <File name="wi-wmo4680" src="html/less/mappings/wi-wmo4680.less" />
        <File name="wi-wunderground" src="html/less/mappings/wi-wunderground.less" />
        <File name="wi-yahoo" src="html/less/mappings/wi-yahoo.less" />
        <File name="weather-icons-classes" src="html/less/weather-icons-classes.less" />
        <File name="weather-icons-core" src="html/less/weather-icons-core.less" />
        <File name="weather-icons-variables" src="html/less/weather-icons-variables.less" />
        <File name="weather-icons-wind" src="html/less/weather-icons-wind.less" />
        <File name="weather-icons-wind.min" src="html/less/weather-icons-wind.min.less" />
        <File name="weather-icons" src="html/less/weather-icons.less" />
        <File name="weather-icons.min" src="html/less/weather-icons.min.less" />
        <File name="classes-beaufort" src="html/sass/icon-classes/classes-beaufort.scss" />
        <File name="classes-day" src="html/sass/icon-classes/classes-day.scss" />
        <File name="classes-direction" src="html/sass/icon-classes/classes-direction.scss" />
        <File name="classes-misc" src="html/sass/icon-classes/classes-misc.scss" />
        <File name="classes-moon-aliases" src="html/sass/icon-classes/classes-moon-aliases.scss" />
        <File name="classes-moon" src="html/sass/icon-classes/classes-moon.scss" />
        <File name="classes-neutral" src="html/sass/icon-classes/classes-neutral.scss" />
        <File name="classes-night" src="html/sass/icon-classes/classes-night.scss" />
        <File name="classes-time" src="html/sass/icon-classes/classes-time.scss" />
        <File name="classes-wind-aliases" src="html/sass/icon-classes/classes-wind-aliases.scss" />
        <File name="classes-wind-degrees" src="html/sass/icon-classes/classes-wind-degrees.scss" />
        <File name="classes-wind" src="html/sass/icon-classes/classes-wind.scss" />
        <File name="variables-beaufort" src="html/sass/icon-variables/variables-beaufort.scss" />
        <File name="variables-day" src="html/sass/icon-variables/variables-day.scss" />
        <File name="variables-direction" src="html/sass/icon-variables/variables-direction.scss" />
        <File name="variables-misc" src="html/sass/icon-variables/variables-misc.scss" />
        <File name="variables-moon" src="html/sass/icon-variables/variables-moon.scss" />
        <File name="variables-neutral" src="html/sass/icon-variables/variables-neutral.scss" />
        <File name="variables-night" src="html/sass/icon-variables/variables-night.scss" />
        <File name="variables-time" src="html/sass/icon-variables/variables-time.scss" />
        <File name="variables-wind-names" src="html/sass/icon-variables/variables-wind-names.scss" />
        <File name="wi-forecast-io" src="html/sass/mappings/wi-forecast-io.scss" />
        <File name="wi-owm" src="html/sass/mappings/wi-owm.scss" />
        <File name="wi-wmo4680" src="html/sass/mappings/wi-wmo4680.scss" />
        <File name="wi-wunderground" src="html/sass/mappings/wi-wunderground.scss" />
        <File name="wi-yahoo" src="html/sass/mappings/wi-yahoo.scss" />
        <File name="weather-icons-classes" src="html/sass/weather-icons-classes.scss" />
        <File name="weather-icons-core" src="html/sass/weather-icons-core.scss" />
        <File name="weather-icons-variables" src="html/sass/weather-icons-variables.scss" />
        <File name="weather-icons-wind.min" src="html/sass/weather-icons-wind.min.scss" />
        <File name="weather-icons-wind" src="html/sass/weather-icons-wind.scss" />
        <File name="weather-icons.min" src="html/sass/weather-icons.min.scss" />
        <File name="weather-icons" src="html/sass/weather-icons.scss" />
        <File name="wi-alien" src="html/svg/wi-alien.svg" />
        <File name="wi-barometer" src="html/svg/wi-barometer.svg" />
        <File name="wi-celsius" src="html/svg/wi-celsius.svg" />
        <File name="wi-cloud-down" src="html/svg/wi-cloud-down.svg" />
        <File name="wi-cloud-refresh" src="html/svg/wi-cloud-refresh.svg" />
        <File name="wi-cloud-up" src="html/svg/wi-cloud-up.svg" />
        <File name="wi-cloud" src="html/svg/wi-cloud.svg" />
        <File name="wi-cloudy-gusts" src="html/svg/wi-cloudy-gusts.svg" />
        <File name="wi-cloudy-windy" src="html/svg/wi-cloudy-windy.svg" />
        <File name="wi-cloudy" src="html/svg/wi-cloudy.svg" />
        <File name="wi-day-cloudy-gusts" src="html/svg/wi-day-cloudy-gusts.svg" />
        <File name="wi-day-cloudy-high" src="html/svg/wi-day-cloudy-high.svg" />
        <File name="wi-day-cloudy-windy" src="html/svg/wi-day-cloudy-windy.svg" />
        <File name="wi-day-cloudy" src="html/svg/wi-day-cloudy.svg" />
        <File name="wi-day-fog" src="html/svg/wi-day-fog.svg" />
        <File name="wi-day-hail" src="html/svg/wi-day-hail.svg" />
        <File name="wi-day-haze" src="html/svg/wi-day-haze.svg" />
        <File name="wi-day-light-wind" src="html/svg/wi-day-light-wind.svg" />
        <File name="wi-day-lightning" src="html/svg/wi-day-lightning.svg" />
        <File name="wi-day-rain-mix" src="html/svg/wi-day-rain-mix.svg" />
        <File name="wi-day-rain-wind" src="html/svg/wi-day-rain-wind.svg" />
        <File name="wi-day-rain" src="html/svg/wi-day-rain.svg" />
        <File name="wi-day-showers" src="html/svg/wi-day-showers.svg" />
        <File name="wi-day-sleet-storm" src="html/svg/wi-day-sleet-storm.svg" />
        <File name="wi-day-sleet" src="html/svg/wi-day-sleet.svg" />
        <File name="wi-day-snow-thunderstorm" src="html/svg/wi-day-snow-thunderstorm.svg" />
        <File name="wi-day-snow-wind" src="html/svg/wi-day-snow-wind.svg" />
        <File name="wi-day-snow" src="html/svg/wi-day-snow.svg" />
        <File name="wi-day-sprinkle" src="html/svg/wi-day-sprinkle.svg" />
        <File name="wi-day-storm-showers" src="html/svg/wi-day-storm-showers.svg" />
        <File name="wi-day-sunny-overcast" src="html/svg/wi-day-sunny-overcast.svg" />
        <File name="wi-day-sunny" src="html/svg/wi-day-sunny.svg" />
        <File name="wi-day-thunderstorm" src="html/svg/wi-day-thunderstorm.svg" />
        <File name="wi-day-windy" src="html/svg/wi-day-windy.svg" />
        <File name="wi-degrees" src="html/svg/wi-degrees.svg" />
        <File name="wi-direction-down-left" src="html/svg/wi-direction-down-left.svg" />
        <File name="wi-direction-down-right" src="html/svg/wi-direction-down-right.svg" />
        <File name="wi-direction-down" src="html/svg/wi-direction-down.svg" />
        <File name="wi-direction-left" src="html/svg/wi-direction-left.svg" />
        <File name="wi-direction-right" src="html/svg/wi-direction-right.svg" />
        <File name="wi-direction-up-left" src="html/svg/wi-direction-up-left.svg" />
        <File name="wi-direction-up-right" src="html/svg/wi-direction-up-right.svg" />
        <File name="wi-direction-up" src="html/svg/wi-direction-up.svg" />
        <File name="wi-dust" src="html/svg/wi-dust.svg" />
        <File name="wi-earthquake" src="html/svg/wi-earthquake.svg" />
        <File name="wi-fahrenheit" src="html/svg/wi-fahrenheit.svg" />
        <File name="wi-fire" src="html/svg/wi-fire.svg" />
        <File name="wi-flood" src="html/svg/wi-flood.svg" />
        <File name="wi-fog" src="html/svg/wi-fog.svg" />
        <File name="wi-gale-warning" src="html/svg/wi-gale-warning.svg" />
        <File name="wi-hail" src="html/svg/wi-hail.svg" />
        <File name="wi-horizon-alt" src="html/svg/wi-horizon-alt.svg" />
        <File name="wi-horizon" src="html/svg/wi-horizon.svg" />
        <File name="wi-hot" src="html/svg/wi-hot.svg" />
        <File name="wi-humidity" src="html/svg/wi-humidity.svg" />
        <File name="wi-hurricane-warning" src="html/svg/wi-hurricane-warning.svg" />
        <File name="wi-hurricane" src="html/svg/wi-hurricane.svg" />
        <File name="wi-lightning" src="html/svg/wi-lightning.svg" />
        <File name="wi-lunar-eclipse" src="html/svg/wi-lunar-eclipse.svg" />
        <File name="wi-meteor" src="html/svg/wi-meteor.svg" />
        <File name="wi-moon-alt-first-quarter" src="html/svg/wi-moon-alt-first-quarter.svg" />
        <File name="wi-moon-alt-full" src="html/svg/wi-moon-alt-full.svg" />
        <File name="wi-moon-alt-new" src="html/svg/wi-moon-alt-new.svg" />
        <File name="wi-moon-alt-third-quarter" src="html/svg/wi-moon-alt-third-quarter.svg" />
        <File name="wi-moon-alt-waning-crescent-1" src="html/svg/wi-moon-alt-waning-crescent-1.svg" />
        <File name="wi-moon-alt-waning-crescent-2" src="html/svg/wi-moon-alt-waning-crescent-2.svg" />
        <File name="wi-moon-alt-waning-crescent-3" src="html/svg/wi-moon-alt-waning-crescent-3.svg" />
        <File name="wi-moon-alt-waning-crescent-4" src="html/svg/wi-moon-alt-waning-crescent-4.svg" />
        <File name="wi-moon-alt-waning-crescent-5" src="html/svg/wi-moon-alt-waning-crescent-5.svg" />
        <File name="wi-moon-alt-waning-crescent-6" src="html/svg/wi-moon-alt-waning-crescent-6.svg" />
        <File name="wi-moon-alt-waning-gibbous-1" src="html/svg/wi-moon-alt-waning-gibbous-1.svg" />
        <File name="wi-moon-alt-waning-gibbous-2" src="html/svg/wi-moon-alt-waning-gibbous-2.svg" />
        <File name="wi-moon-alt-waning-gibbous-3" src="html/svg/wi-moon-alt-waning-gibbous-3.svg" />
        <File name="wi-moon-alt-waning-gibbous-4" src="html/svg/wi-moon-alt-waning-gibbous-4.svg" />
        <File name="wi-moon-alt-waning-gibbous-5" src="html/svg/wi-moon-alt-waning-gibbous-5.svg" />
        <File name="wi-moon-alt-waning-gibbous-6" src="html/svg/wi-moon-alt-waning-gibbous-6.svg" />
        <File name="wi-moon-alt-waxing-crescent-1" src="html/svg/wi-moon-alt-waxing-crescent-1.svg" />
        <File name="wi-moon-alt-waxing-crescent-2" src="html/svg/wi-moon-alt-waxing-crescent-2.svg" />
        <File name="wi-moon-alt-waxing-crescent-3" src="html/svg/wi-moon-alt-waxing-crescent-3.svg" />
        <File name="wi-moon-alt-waxing-crescent-4" src="html/svg/wi-moon-alt-waxing-crescent-4.svg" />
        <File name="wi-moon-alt-waxing-crescent-5" src="html/svg/wi-moon-alt-waxing-crescent-5.svg" />
        <File name="wi-moon-alt-waxing-crescent-6 " src="html/svg/wi-moon-alt-waxing-crescent-6 .svg" />
        <File name="wi-moon-alt-waxing-gibbous-1" src="html/svg/wi-moon-alt-waxing-gibbous-1.svg" />
        <File name="wi-moon-alt-waxing-gibbous-2" src="html/svg/wi-moon-alt-waxing-gibbous-2.svg" />
        <File name="wi-moon-alt-waxing-gibbous-3" src="html/svg/wi-moon-alt-waxing-gibbous-3.svg" />
        <File name="wi-moon-alt-waxing-gibbous-4" src="html/svg/wi-moon-alt-waxing-gibbous-4.svg" />
        <File name="wi-moon-alt-waxing-gibbous-5" src="html/svg/wi-moon-alt-waxing-gibbous-5.svg" />
        <File name="wi-moon-alt-waxing-gibbous-6 " src="html/svg/wi-moon-alt-waxing-gibbous-6 .svg" />
        <File name="wi-moon-first-quarter" src="html/svg/wi-moon-first-quarter.svg" />
        <File name="wi-moon-full" src="html/svg/wi-moon-full.svg" />
        <File name="wi-moon-new" src="html/svg/wi-moon-new.svg" />
        <File name="wi-moon-third-quarter" src="html/svg/wi-moon-third-quarter.svg" />
        <File name="wi-moon-waning-crescent-1" src="html/svg/wi-moon-waning-crescent-1.svg" />
        <File name="wi-moon-waning-crescent-2" src="html/svg/wi-moon-waning-crescent-2.svg" />
        <File name="wi-moon-waning-crescent-3" src="html/svg/wi-moon-waning-crescent-3.svg" />
        <File name="wi-moon-waning-crescent-4 " src="html/svg/wi-moon-waning-crescent-4 .svg" />
        <File name="wi-moon-waning-crescent-5" src="html/svg/wi-moon-waning-crescent-5.svg" />
        <File name="wi-moon-waning-crescent-6" src="html/svg/wi-moon-waning-crescent-6.svg" />
        <File name="wi-moon-waning-gibbous-1" src="html/svg/wi-moon-waning-gibbous-1.svg" />
        <File name="wi-moon-waning-gibbous-2" src="html/svg/wi-moon-waning-gibbous-2.svg" />
        <File name="wi-moon-waning-gibbous-3" src="html/svg/wi-moon-waning-gibbous-3.svg" />
        <File name="wi-moon-waning-gibbous-4" src="html/svg/wi-moon-waning-gibbous-4.svg" />
        <File name="wi-moon-waning-gibbous-5 " src="html/svg/wi-moon-waning-gibbous-5 .svg" />
        <File name="wi-moon-waning-gibbous-6" src="html/svg/wi-moon-waning-gibbous-6.svg" />
        <File name="wi-moon-waxing-crescent-1" src="html/svg/wi-moon-waxing-crescent-1.svg" />
        <File name="wi-moon-waxing-crescent-2" src="html/svg/wi-moon-waxing-crescent-2.svg" />
        <File name="wi-moon-waxing-crescent-3" src="html/svg/wi-moon-waxing-crescent-3.svg" />
        <File name="wi-moon-waxing-crescent-4" src="html/svg/wi-moon-waxing-crescent-4.svg" />
        <File name="wi-moon-waxing-crescent-5" src="html/svg/wi-moon-waxing-crescent-5.svg" />
        <File name="wi-moon-waxing-crescent-6 " src="html/svg/wi-moon-waxing-crescent-6 .svg" />
        <File name="wi-moon-waxing-gibbous-1" src="html/svg/wi-moon-waxing-gibbous-1.svg" />
        <File name="wi-moon-waxing-gibbous-2" src="html/svg/wi-moon-waxing-gibbous-2.svg" />
        <File name="wi-moon-waxing-gibbous-3" src="html/svg/wi-moon-waxing-gibbous-3.svg" />
        <File name="wi-moon-waxing-gibbous-4 " src="html/svg/wi-moon-waxing-gibbous-4 .svg" />
        <File name="wi-moon-waxing-gibbous-5" src="html/svg/wi-moon-waxing-gibbous-5.svg" />
        <File name="wi-moon-waxing-gibbous-6" src="html/svg/wi-moon-waxing-gibbous-6.svg" />
        <File name="wi-moonrise" src="html/svg/wi-moonrise.svg" />
        <File name="wi-moonset" src="html/svg/wi-moonset.svg" />
        <File name="wi-na" src="html/svg/wi-na.svg" />
        <File name="wi-night-alt-cloudy-gusts" src="html/svg/wi-night-alt-cloudy-gusts.svg" />
        <File name="wi-night-alt-cloudy-high" src="html/svg/wi-night-alt-cloudy-high.svg" />
        <File name="wi-night-alt-cloudy-windy" src="html/svg/wi-night-alt-cloudy-windy.svg" />
        <File name="wi-night-alt-cloudy" src="html/svg/wi-night-alt-cloudy.svg" />
        <File name="wi-night-alt-hail" src="html/svg/wi-night-alt-hail.svg" />
        <File name="wi-night-alt-lightning" src="html/svg/wi-night-alt-lightning.svg" />
        <File name="wi-night-alt-partly-cloudy" src="html/svg/wi-night-alt-partly-cloudy.svg" />
        <File name="wi-night-alt-rain-mix" src="html/svg/wi-night-alt-rain-mix.svg" />
        <File name="wi-night-alt-rain-wind" src="html/svg/wi-night-alt-rain-wind.svg" />
        <File name="wi-night-alt-rain" src="html/svg/wi-night-alt-rain.svg" />
        <File name="wi-night-alt-showers" src="html/svg/wi-night-alt-showers.svg" />
        <File name="wi-night-alt-sleet-storm" src="html/svg/wi-night-alt-sleet-storm.svg" />
        <File name="wi-night-alt-sleet" src="html/svg/wi-night-alt-sleet.svg" />
        <File name="wi-night-alt-snow-thunderstorm" src="html/svg/wi-night-alt-snow-thunderstorm.svg" />
        <File name="wi-night-alt-snow-wind" src="html/svg/wi-night-alt-snow-wind.svg" />
        <File name="wi-night-alt-snow" src="html/svg/wi-night-alt-snow.svg" />
        <File name="wi-night-alt-sprinkle" src="html/svg/wi-night-alt-sprinkle.svg" />
        <File name="wi-night-alt-storm-showers" src="html/svg/wi-night-alt-storm-showers.svg" />
        <File name="wi-night-alt-thunderstorm" src="html/svg/wi-night-alt-thunderstorm.svg" />
        <File name="wi-night-clear" src="html/svg/wi-night-clear.svg" />
        <File name="wi-night-cloudy-gusts" src="html/svg/wi-night-cloudy-gusts.svg" />
        <File name="wi-night-cloudy-high" src="html/svg/wi-night-cloudy-high.svg" />
        <File name="wi-night-cloudy-windy" src="html/svg/wi-night-cloudy-windy.svg" />
        <File name="wi-night-cloudy" src="html/svg/wi-night-cloudy.svg" />
        <File name="wi-night-fog" src="html/svg/wi-night-fog.svg" />
        <File name="wi-night-hail" src="html/svg/wi-night-hail.svg" />
        <File name="wi-night-lightning" src="html/svg/wi-night-lightning.svg" />
        <File name="wi-night-partly-cloudy" src="html/svg/wi-night-partly-cloudy.svg" />
        <File name="wi-night-rain-mix" src="html/svg/wi-night-rain-mix.svg" />
        <File name="wi-night-rain-wind" src="html/svg/wi-night-rain-wind.svg" />
        <File name="wi-night-rain" src="html/svg/wi-night-rain.svg" />
        <File name="wi-night-showers" src="html/svg/wi-night-showers.svg" />
        <File name="wi-night-sleet-storm" src="html/svg/wi-night-sleet-storm.svg" />
        <File name="wi-night-sleet" src="html/svg/wi-night-sleet.svg" />
        <File name="wi-night-snow-thunderstorm" src="html/svg/wi-night-snow-thunderstorm.svg" />
        <File name="wi-night-snow-wind" src="html/svg/wi-night-snow-wind.svg" />
        <File name="wi-night-snow" src="html/svg/wi-night-snow.svg" />
        <File name="wi-night-sprinkle" src="html/svg/wi-night-sprinkle.svg" />
        <File name="wi-night-storm-showers" src="html/svg/wi-night-storm-showers.svg" />
        <File name="wi-night-thunderstorm" src="html/svg/wi-night-thunderstorm.svg" />
        <File name="wi-rain-mix" src="html/svg/wi-rain-mix.svg" />
        <File name="wi-rain-wind" src="html/svg/wi-rain-wind.svg" />
        <File name="wi-rain" src="html/svg/wi-rain.svg" />
        <File name="wi-raindrop" src="html/svg/wi-raindrop.svg" />
        <File name="wi-raindrops" src="html/svg/wi-raindrops.svg" />
        <File name="wi-refresh-alt" src="html/svg/wi-refresh-alt.svg" />
        <File name="wi-refresh" src="html/svg/wi-refresh.svg" />
        <File name="wi-sandstorm" src="html/svg/wi-sandstorm.svg" />
        <File name="wi-showers" src="html/svg/wi-showers.svg" />
        <File name="wi-sleet" src="html/svg/wi-sleet.svg" />
        <File name="wi-small-craft-advisory" src="html/svg/wi-small-craft-advisory.svg" />
        <File name="wi-smog" src="html/svg/wi-smog.svg" />
        <File name="wi-smoke" src="html/svg/wi-smoke.svg" />
        <File name="wi-snow-wind" src="html/svg/wi-snow-wind.svg" />
        <File name="wi-snow" src="html/svg/wi-snow.svg" />
        <File name="wi-snowflake-cold" src="html/svg/wi-snowflake-cold.svg" />
        <File name="wi-solar-eclipse" src="html/svg/wi-solar-eclipse.svg" />
        <File name="wi-sprinkle" src="html/svg/wi-sprinkle.svg" />
        <File name="wi-stars" src="html/svg/wi-stars.svg" />
        <File name="wi-storm-showers" src="html/svg/wi-storm-showers.svg" />
        <File name="wi-storm-warning" src="html/svg/wi-storm-warning.svg" />
        <File name="wi-strong-wind" src="html/svg/wi-strong-wind.svg" />
        <File name="wi-sunrise" src="html/svg/wi-sunrise.svg" />
        <File name="wi-sunset" src="html/svg/wi-sunset.svg" />
        <File name="wi-thermometer-exterior" src="html/svg/wi-thermometer-exterior.svg" />
        <File name="wi-thermometer-internal" src="html/svg/wi-thermometer-internal.svg" />
        <File name="wi-thermometer" src="html/svg/wi-thermometer.svg" />
        <File name="wi-thunderstorm" src="html/svg/wi-thunderstorm.svg" />
        <File name="wi-time-1" src="html/svg/wi-time-1.svg" />
        <File name="wi-time-10" src="html/svg/wi-time-10.svg" />
        <File name="wi-time-11" src="html/svg/wi-time-11.svg" />
        <File name="wi-time-12" src="html/svg/wi-time-12.svg" />
        <File name="wi-time-2" src="html/svg/wi-time-2.svg" />
        <File name="wi-time-3" src="html/svg/wi-time-3.svg" />
        <File name="wi-time-4" src="html/svg/wi-time-4.svg" />
        <File name="wi-time-5" src="html/svg/wi-time-5.svg" />
        <File name="wi-time-6" src="html/svg/wi-time-6.svg" />
        <File name="wi-time-7" src="html/svg/wi-time-7.svg" />
        <File name="wi-time-8" src="html/svg/wi-time-8.svg" />
        <File name="wi-time-9" src="html/svg/wi-time-9.svg" />
        <File name="wi-tornado" src="html/svg/wi-tornado.svg" />
        <File name="wi-train" src="html/svg/wi-train.svg" />
        <File name="wi-tsunami" src="html/svg/wi-tsunami.svg" />
        <File name="wi-umbrella" src="html/svg/wi-umbrella.svg" />
        <File name="wi-volcano" src="html/svg/wi-volcano.svg" />
        <File name="wi-wind-beaufort-0" src="html/svg/wi-wind-beaufort-0.svg" />
        <File name="wi-wind-beaufort-1" src="html/svg/wi-wind-beaufort-1.svg" />
        <File name="wi-wind-beaufort-10" src="html/svg/wi-wind-beaufort-10.svg" />
        <File name="wi-wind-beaufort-11" src="html/svg/wi-wind-beaufort-11.svg" />
        <File name="wi-wind-beaufort-12" src="html/svg/wi-wind-beaufort-12.svg" />
        <File name="wi-wind-beaufort-2" src="html/svg/wi-wind-beaufort-2.svg" />
        <File name="wi-wind-beaufort-3" src="html/svg/wi-wind-beaufort-3.svg" />
        <File name="wi-wind-beaufort-4" src="html/svg/wi-wind-beaufort-4.svg" />
        <File name="wi-wind-beaufort-5" src="html/svg/wi-wind-beaufort-5.svg" />
        <File name="wi-wind-beaufort-6" src="html/svg/wi-wind-beaufort-6.svg" />
        <File name="wi-wind-beaufort-7" src="html/svg/wi-wind-beaufort-7.svg" />
        <File name="wi-wind-beaufort-8" src="html/svg/wi-wind-beaufort-8.svg" />
        <File name="wi-wind-beaufort-9" src="html/svg/wi-wind-beaufort-9.svg" />
        <File name="wi-wind-deg" src="html/svg/wi-wind-deg.svg" />
        <File name="wi-windy" src="html/svg/wi-windy.svg" />
        <File name="weathericons" src="html/values/weathericons.xml" />
    </Resources>
    <Topics />
    <IgnoredPaths />
    <Translations auto-fill="en_US">
        <Translation name="translation_en_US" src="translations/translation_en_US.ts" language="en_US" />
    </Translations>
</Package>
